// Copyright © 2021 Ni Fu. All rights reserved.

import Foundation

class ContentResource {
    
    static let CURRENCIES = ["$", "¢", "£", "¥", "؋", "৳", "₠", "૱", "௹", "฿"]
    
    static let EMOTICONS = ["ヾ(ﾟдﾟ)ﾉ゛", "ヽ(ﾟω､ﾟ)ﾉ", "ヾ(o´∀`o)ﾉ", "ヽ(･ω･´ﾒ)", "ヾ(●´∀`●)",
                    "ヾ(=･ω･=)o", "ヽ(´Ａ`)ﾉ", "ヽ(´ｰ`)ﾉ", "ヽ(;´Д`)ﾉ", "ヾ(*ﾟω∩*)",
                    "彡(-_-;)彡", "(((ﾟДﾟ)))", "ﾉ)ﾟДﾟ(ヽ", "つ;´･ω-)つ", "щ(`ω´щ)",
                    "Ψ(`∀´)Ψ", "ΣΣ(ﾟдﾟlll)!", "Σ(ﾟДﾟ;≡;ﾟдﾟ)", "(;:ﾟ:ж:ﾟ:;)", "(｡-д-｡)ゞ",
                    "(*´～`*)", "(´;ω;`)", "m(_ _)m", "《(;´Д`)》", "～(´ｰ`～)",
                    "((((；ﾟДﾟ))))ｶﾞｸｶﾞｸﾌﾞﾙﾌﾞﾙ", "(((;°Д°;))))", "((.;ﾟ;:Д:;ﾟ;.))", "(*°ρ°*)", "_:(´ཀ`」 ∠):_",
                    "_(:o 」∠)_", "(╯•ω•╰) I’m sorry…", "(´･_･人)", "ｳﾜｧｧ━━━｡ﾟ(ﾟ´Д｀ﾟ)ﾟ｡━━━ﾝ!!!!", "ｷﾀ━━━━(ﾟ∀ﾟ)━━━━!!",
                    "きゃ━(;´༎ຶД༎ຶ`)━っっ!!!", ":;((っ°ө°ｃ));:", "ﾆﾔﾆﾔ(°∀° )ﾆﾔﾆﾔ", "(； ･`ω･´)ﾅﾝ…ﾀﾞﾄ!?", "∑( ◦д⊙)!!",
                    "∑Σ( °∀°ﾉ)ﾉ", "ｱﾜ((ﾟﾟддﾟﾟ ))ﾜﾜ!!", "(・∀・)Good!!", "(´-﹏-`；)", "(๑･﹃ ･｀๑)ｼﾞｭﾙﾘ",
                    "‹‹\\(´ω` )/››‹‹\\( 　´)/›› ‹‹\\( ´ω`)/››~♪", "(・(・(・(・д・)・)・)・) ﾌﾞﾝｼｰﾝ!!",
                    "₍₍⁽⁽(ง ˙o˙)ว₎₎⁾⁾ ｳﾎﾎ ｳﾎ", "へ(ﾟ∀ﾟへ)ｵﾊﾞｹｪ～", "(((ง’ω’)و三 ง’ω’)ڡ≡ｼｭｯｼｭ", "─=≡Σ((( つ•̀ω•́)つ",
                    "┏┗(´ิq´ิ)┓┛ｷｪｪｪｪｨｲｲｲｲｲ", "(‘ω’)三(ε: )三(.ω.)三( :3 )三(‘ω’)", "(`･ω･´)ゞﾋﾞｼｯ!!",
                     "(^_^)", "ｳｲﾝｸ(^_-)-☆", "（⌒▽⌒", "＼(~o~)／", "(^0_0^)", "＼(^o^)／", "^O^ｱｰｰｰﾝ",
                     "(^_^)!ﾋﾟﾝﾎﾟｰﾝ", "(^Ｑ^)ｱｰｰﾝ", "(⌒^⌒)ｂ", "p(^^)q", "ﾜｰｲ!(^Ｏ^)", "(^Q^)", "( ^)o(^ )",
                     "o(^-^)o", "(^з^)-☆Chu!!", "(^-^)vｲｴｲ!", "(^o^)＼(^^ )ﾖｼﾖｼ", "(￣▽￣)Ｖ ", "ｲｴｰｲ    (#^_^#)",
                     "(*^o^*)", "((*´∀))ｹﾗｹﾗ", "ﾎﾟﾘﾎﾟﾘf(^_^;", "ヾ(*´∀｀*)ﾉｷｬｯｷｬ", "(^^ゞﾃﾚﾃﾚ", "（*ゝ∀・*）",
                     "ﾍﾍ（^^;", "(๑´ლ๑)ﾌﾌ♡", "ﾍ(･_･ﾍ)ｴﾍﾍ", "\\( ˆoˆ )/", "<(￣＾￣)>ｴｯﾍﾝ", "˖°٩( ‘ω’ )و", "٩(ˊᗜˋ*)و",
                     "(o*ﾟｰﾟ)oﾜｸﾜｸ", "o(ˊ▽ˋ*)oﾜｸﾜｸ", "(*n’∀’)n ﾊﾞﾝｻﾞｰｲ", "(*´▽*)❀", "d( *＾ω＾*)pﾔｯﾀｰ!",
                     "(*ﾟ▽ﾟ*)ワクワク", "*\\(^o^)/*", "\\( ˆoˆ )/", "(笑´ｗ｀)", "(￣ー￣)ﾆﾔﾘｯ", "\\( º∀º )/♪",
                     "(*´∇*)", "(●´▽｀)ﾅﾊﾊ", "（￣ー＋￣）ニカッ！", "＼(^~^)／", "ヽ（●´3｀）ノ゛", "(￣￣▽￣￣)",
                     "ｷﾀ━━━━(ﾟ∀ﾟ)━━━━!!", "ｷｬ━━━━(ﾟ∀ﾟ)━━━━!!", "(T-T)", "(ﾉ∇･､)ｸｽﾝ", "(T.T)", "（ｐ>□<ｑ*））",
                     "｡ﾟ(Ｔ^Ｔ)ﾟ｡ﾟ", "(ノω=;)。。。", "(*6_6)o/~ﾊﾞｲﾊﾞｲ", "( ﾉД)ｼｸｼｸ…", "ヽ(≧Д≦)ノｳﾜｧｧﾝ!!",
                     "(´ﾉω･｀*)ﾅｹﾙ－", "(´Д｀。)ｸﾞｽﾝ", "。゜(つω｀）゜。", "(´Ａ｀。)ｸﾞｽﾝ", "(´ﾉωﾉ)ﾒｿﾒｿ",
                     "(´＿｀。)ｸﾞｽﾝ", "(PДq｡)", "・゜・(つД｀)・゜・", "(´；д；)ﾌﾞﾜｯ", "・゜゜・(/□＼*)・゜゜・わ～ん",
                     "|ω；｀)ｳﾘｭﾘｭ｡｡", "( *´ｘ艸ｘ｀)ｳｳｯ..", "ﾄﾞﾊﾞｰｯ（┬┬＿┬┬）涙", "o(TヘTo) くぅ", "((((((((((((*ﾉﾉ) ﾋﾄﾞｲﾜｰｯ",
                     "( T-T) ｳﾙｳﾙ", "号(┳Д┳)泣", "（ ´Д⊂ヽエーーン", "(´　ε　｀。･｡)ｸｽﾝ", "ｴｰﾝ!o(TヘT o)",
                     "(´；ω；)ｳｯ", "（つд；*)ﾆｬﾝ…", "(　；∀；) ｶﾅｼｲﾅｰ", "(/へ＼*)ｳｩ、ﾋｯｸ", "｡ﾟ(ﾟ´⊃д･*)ﾟ｡+｡ｪ－ﾝ",
                     "。ﾟ(ﾟﾉД｀ﾟ)ﾟ｡ｩﾜｰﾝｯ", "｡+ﾟ(ﾟつ皿ﾟ)ﾟ+｡ﾜｧｧﾝ!!", "｡･ﾟ(´pωq｀)ﾟ･｡", "（ΩДΩ）号泣", "（´・-・。）ｸｽﾝ",
                     "。*゜(PД｀ﾟ)ﾟ｡わーん", "(´Δ´)・・・oｏｳﾜｰﾝ", "゜・（ｘ ω ｘ）・゜。", "(･∀･;)", "（´ω｀）ﾄﾎﾎ…",
                     "( ˙▿˙ ; )", "(｡•́︿ •̀｡)", "(–;", "(^^;", "(..;)", "(･_･;", "(･_ ; )", "(..;)",
                     "(‘Д｀)y-~~ｿｰﾅﾉ", "(-_-;", "（；´д｀）ノ ", "いや～    (^_^;A", "(_ _;)。。", "(^_^;ゞ",
                     "0(T_T)0", "ｷﾞｸｯ(-_＾；)", "o(T^T)o", "（＾◇＾；", "(ﾟ_ﾟゝ", "＼(^^:;)…ﾏｱﾏｱ", "／(-_-)＼",
                     "（ _ _ ）”", "(_-_)", "ε= (・c_,･｡A)ﾌｳｰ", "|(-_-)|ｷｺｴﾅｲ…", "(´∀｀; )", "(ﾟﾟ )( ﾟﾟ)ｷｮﾛｷｮﾛ",
                     "ε- (-●_-o) ﾊﾌ-ﾝ…", "(･･ )( ･･)ｷｮﾛｷｮﾛ", "(¯―¯٥)", "（θ_θ;）ﾔﾚﾔﾚ", "ﾌｩ(o´Å｀)=з", "（￣～￣）ξ",
                     "(⌒-⌒; )", "ε=（＠．＠；） ｳｯﾌﾟ", "ε=（×。×）ﾊｧ…。", "(^_^;", "(；・□・)ｴｴ..", "(°ﾛ°；)",
                     "(ﾉc_,･;)ﾊｱ･･･", "(´)=3", "( ° 皿° ;; )", "(´-﹏-；)", "(￣Д)＝３", "ﾌｩ(o´Å｀)=з",
                     "( ˘ω˘ ; )・・・。", "(((;´•ω•;)))", "(。・ε・。)", "(￣Д￣；)＝３ﾊｧ..", "(;Д;ﾟ；)",
                     "(#･∀･)ﾑｶﾑｶ", "((“o(>ω<)o”))クヤシイー!!", "(*’へ’*)ぷんぷん", "｡･”(＞0＜)”･｡ﾝﾓｫ～",
                     "（╬0∀0）=3ﾊｧ.", "q(-.-;)p?", "(-_- )凸", "(-_-#", "(-“- )", "(-_-ﾒ)", "ﾊﾟｰﾝﾁo(ﾟ◇ﾟ)○",
                     "ﾁｪｯ(-｡ -; )", "ﾊﾞｺｯ(-_-;)=◎", "ﾁｪｯ!(-ε-)", "ﾊﾟﾝﾁo(_’)○", "ﾎﾞｶｯ＝○)゜o゜)☆", "(ﾟ.ﾟ ) ＼(-´)",
                     "(._+)☆＼(-.-メ)ﾍﾟｼｯ", "(▼▼ﾒ)ﾅﾝﾀﾞﾄｫ", "(ﾟoﾟC=(__;ﾊﾞｷｯ", "（｀－´）ﾓｳ!", "o(･_･θキック",
                     "(｀□´)ｺﾗｯ!", "ﾝﾓｫｰ!! o(*≧д≦)o″))", "★O=(_ )ﾊﾟﾝﾁ!", "(# ﾟДﾟ)つ〃∩ ｺﾞﾙｧ", "“o(▼皿▼メ;)o”ﾌﾟﾙﾌﾟﾙ",
                     "o(｀･･_,´ﾒ)oﾌﾟﾝｽｶ!!", "((“o(ﾟ∩ﾟ*)ﾌﾟﾙﾌﾟﾙ･･", "ヽ(#｀_つ´)ﾉﾌﾟﾝｽｺ!!!!", "“o(￣‐￣*)　ﾌﾟﾙﾌﾟﾙ",
                     "(´‐｀ ○）＼(○｀ε´○) ｺﾗ!ｺﾗ!", "| ｀Д´|ﾉこらぁ！", "o(怒･ｪ･´)ﾉ ｺﾘｬｰ!!", "((o(>皿<)o)) ｷｨｨｨ!!",
                     "(。-ω´-)", "(－＂－怒)", "~l(≧∇≦)l~ ｳﾙｻｰｲ!", "(｡･ˇдˇ･｡)", "ε=ε=ε=(#・д・)/ ｺﾗｧｰ!!",
                     "(# ﾟДﾟ)ｺﾞﾙｧ!!", "(｡・∀・)ﾖﾛｼｸ♪", "(m。_。)m ｵﾈｶﾞｲｼﾏｽ", "(^O^)/ｵｰｲ", "ﾊﾝｾｲ□＼(.. )",
                     "(_o_)ｵｰｲ", "ﾘｮｳｶｲ!∠(^_^)", "あのうヽ(^_^;)", "ﾘｮｳｶｲ!(^-^ゝ", "ﾁｮｯﾄﾁｮｯﾄヾ(^_^", "ｻｱ…┐(-。-;)┌",
                     "ﾊｰｲ(^o^)／", "ヽ(´ｰ)丿ﾌｳ", "♪(／°°)／￣ハィ", "ﾔｱ!＼(^_^ )", "(^-^)/~~~", "?( ^_^)／ﾔｱ!",
                     "＼( ^ ^)/～〃ﾊﾞｲﾊﾞｲ", "＼(^_^ )", "ﾊﾞｲﾊﾞｲ(;_;)/~~~", "( ^_^)／ﾄﾞﾓﾄﾞﾓ", "　）))))‘‘）/~~~ ﾊﾞｲﾊﾞ～ｲ!",
                     "m(_ _)mﾍﾟｺﾘ", "ｺﾞﾒﾝﾈ(・人・；)", "ｺﾞﾒﾝ<(_ _)>", "(ﾟ∇^*)ｵﾊﾖ♪", "(っ´Ι)っ { おはよう",
                     "(o｡･･｡)o　ぉは～", "才ﾉヽ∋―_φ(ﾟ▽ﾟ*)♪", "(^-^*)/ｺﾝﾁｬ！", "*･ω･)ﾉ こん♪", "(ﾟ∇^*)ｺﾝﾆﾁﾜ",
                     "。・∀・)ノ゛ｺﾝﾆﾁﾊ", "ヾ(´c_,｀*)ﾊﾞﾝﾜｧ～★", "(｡uωu)＜こんばんゎ", "( ^_^)／ｺﾝﾊﾞﾝﾊ", "(oﾟ▽ﾟ)oｺﾝﾊﾞﾝﾜ",
                     "ﾏﾀｸﾙﾈ |･x･)ﾉ|Ю", "ε=┏(*`＞ω<)┛ｼﾞｬｧﾈ", "|´▽｀●)ﾉ |Ю 　| ｲｯﾃｷﾏｰｽ", "ｲｯﾃｷﾏｰｽ（っ・∀・）っ",
                     "(・∀・)b OK!", "v(*’-^*)-☆ ok!", "（。＾Д＾。）／OK!", "(*｀д´)ｂ全然OK", "(o￣∇￣)ノそうだよ♪",
                     "（●´∀｀）b そぅ☆", "d(ゝc_，・。)ｿｳｿｳ♪", "(｀・∀+´・)b そうだ！！", "(゜Д゜)ゞ了解!!",
                     "d(´∀｀　)了解", "ﾗｼﾞｬ(*・ω・)ゞ⌒☆", "(*´∀｀)ゞﾗｼﾞｬ!", "(≧ω≦。)プププ", "ｸｽ(･m･*)ｸｽ",
                     "(≧Σ≦)ぶっ！", "(_≧Д≦)ノ彡☆ばんばん", "ぷぷ(*￣m￣)o))", "( ´艸｀)ﾑﾌﾟﾌﾟ", "(*ﾟ▽ﾉﾟ*)おほほほ♪",
                     "ﾜﾊﾊo(*^▽^*)o ｹﾗｹﾗ", "( ≧∇≦)ﾌﾞﾊﾊﾊﾊｯ", "∬≧ω≦):;*.’:;", "(´∇ﾉ｀*)ｵﾎﾎ♪", "(☆ﾟ∀ﾟ)ｱﾊﾊﾊ",
                     "(　ﾟ,_ゝﾟ）ｯﾌﾟ", "((爆´∀｀笑))", "(ノ∀￣〃)ノ彡", "(≧w≦)ｳｼｼ", "(￣∇￣；) ﾊｯﾊｯﾊ…", "(p∇б★)",
                     "(´0｀*)♪", "(*｀皿´*) ｳｼｼ", "(〃^∇^)o彡☆♪", "(-ι- ) クックック", "ヾ(@^▽^@)ノ",
                     "ヽ(´▽｀)/爆笑", "(＾▽＾／)", "(≧ε≦●)ﾉ彡", "(^_^;)＼(‘_’) ｵｲｵｲ", "(･_･)ヾ(^o^;) ｵｲｵｲ",
                     "(ﾟﾟ;)＼(–;)ｵｲｵｲ", "ヾ(–;)ぉぃぉぃ", "＼(- -;)ﾅﾝﾃﾞﾔﾈﾝ", "ヾ(~∇~;) ｺﾚｺﾚ", "(-_-;)ﾑｼﾑｼ",
                     "ﾍ(..､ﾍ)☆＼(ﾟﾛﾟ )ﾅﾝﾃﾞﾔﾈﾝ!", "(ﾟ_｡)ｽﾞﾙｯ", "ヾ(-д-;)ぉぃぉぃ", "((((((;_ _)", "ヾ(･･ )ｫｨｫｨ",
                     "(((((((^_^;)", "(;-o-)σｫｨｫｨ・・・", "(((((((;^^)", "Σ＼(￣ｰ￣;)ﾅﾝﾃﾞﾔﾈﾝ", "．．．．．．．．( ..)",
                     "ﾅﾝﾃﾞﾔﾈﾝ!!(；＝＝)ノ", "（‥　）))))", "＼(￣ ￣*)ﾊﾞｼｯ", "(‘o’;)ｫｨｫｨｫｨ", "ヾ(~O~;) ｺﾘｬｺﾘｬ",
                     "(・ε・。)ﾅﾝﾃﾞﾔﾈﾝ", ";･_･)_θ☆ﾋﾞｼｯ", "ゞ(￣∇￣;)ｽﾞﾙｯ", "ﾂｯｺﾐ(^o^)ノ☆/;^-^)ノ"]
    
    static let COBOL = [ "ACCEPT", "ACCESS", "ADD", "ADDRESS", "ADVANCING", "AFTER", "ALL", "ALPHABET",
                  "ALPHABETIC", "ALPHABETIC-LOWER", "ALPHABETIC-UPPER", "ALPHANUMERIC",
                  "ALPHANUMERIC-EDITED", "ALSO", "ALTER", "ALTERNATE", "AND", "ANY", "APPLY",
                  "ARE", "AREA", "AREAS", "ASCENDING", "ASSIGN", "AT", "AUTHOR", "BASIS", "BEFORE",
                  "BEGINNING", "BINARY", "BLANK", "BLOCK", "BOTTOM", "BY", "CALL", "CANCEL", "CBL",
                  "CD", "CF", "CH", "CHARACTER", "CHARACTERS", "CLASS", "CLASS-ID", "CLOCK-UNITS",
                  "CLOSE", "COBOL", "CODE", "CODE-SET", "COLLATING", "COLUMN", "COM-REG", "COMMA",
                  "COMMON", "COMMUNICATION", "COMP", "COMP-1", "COMP-2", "COMP-3", "COMP-4", "COMP-5",
                  "COMPUTATIONAL", "COMPUTATIONAL-1", "COMPUTATIONAL-2", "COMPUTATIONAL-3", "COMPUTATIONAL-4",
                  "COMPUTATIONAL-5", "COMPUTE", "CONFIGURATION", "CONTAINS", "CONTENT", "CONTINUE",
                  "CONTROL", "CONTROLS", "CONVERTING", "COPY", "CORR", "CORRESPONDING", "COUNT", "CURRENCY",
                  "DATA", "DATE-COMPILED", "DATE-WRITTEN", "DAY", "DAY-OF-WEEK", "DBCS", "DE", "DEBUG-CONTENTS",
                  "DEBUG-ITEM", "DEBUG-LINE", "DEBUG-NAME", "DEBUG-SUB-1", "DEBUG-SUB-2", "DEBUG-SUB-3",
                  "DEBUGGING", "DECIMAL-POINT", "DECLARATIVES", "DELETE", "DELIMITED", "DELIMITER",
                  "DEPENDING", "DESCENDING", "DESTINATION", "DETAIL", "DISPLAY", "DISPLAY-1", "DIVIDE",
                  "DIVISION", "DOWN", "DUPLICATES", "DYNAMIC", "EGCS", "EGI", "EJECT", "ELSE", "EMI",
                  "ENABLE", "END", "END-ADD", "END-CALL", "END-COMPUTE", "END-DELETE", "END-DIVIDE",
                  "END-EVALUATE", "END-IF", "END-INVOKE", "END-MULTIPLY", "END-OF-PAGE", "END-PERFORM",
                  "END-READ", "END-RECEIVE", "END-RETURN", "END-REWRITE", "END-SEARCH", "END-START",
                  "END-STRING", "END-SUBTRACT", "END-UNSTRING", "END-WRITE", "ENDING", "ENTER", "ENTRY",
                  "ENVIRONMENT", "EOP", "EQUAL", "ERROR", "ESI", "EVALUATE", "EVERY", "EXCEPTION",
                  "EXIT", "EXTEND", "EXTERNAL", "FALSE", "FD", "FILE", "FILE-CONTROL", "FILLER",
                  "FINAL", "FIRST", "FOOTING", "FOR", "FROM", "FUNCTION", "GENERATE", "GIVING",
                  "GLOBAL", "GO", "GOBACK", "GREATER", "GROUP", "HEADING", "HIGH-VALUE", "HIGH-VALUES",
                  "I-O", "I-O-CONTROL", "ID", "IDENTIFICATION", "IF", "IN", "INDEX", "INDEXED",
                  "INDICATE", "INHERITS", "INITIAL", "INITIALIZE", "INITIATE", "INPUT", "INPUT-OUTPUT",
                  "INSERT", "INSPECT", "INSTALLATION", "INTO", "INVALID", "INVOKE", "IS", "JUST", "JUSTIFIED",
                  "KANJI KEY", "LABEL", "LAST", "LEADING", "LEFT", "LENGTH", "LESS", "LIMIT", "LIMITS",
                  "LINAGE", "LINAGE-COUNTER", "LINE", "LINE-COUNTER", "LINES", "LINKAGE", "LOCAL-STORAGE",
                  "LOCK", "LOW-VALUE", "LOW-VALUES", "MEMORY", "MERGE", "MESSAGE", "METACLASS", "METHOD",
                  "METHOD-ID", "MODE", "MODULES", "MORE-LABELS", "MOVE", "MULTIPLE", "MULTIPLY", "NATIVE",
                  "NATIVE_BINARY", "NEGATIVE", "NEXT", "NO", "NOT", "NULL", "NULLS", "NUMBER", "NUMERIC",
                  "NUMERIC-EDITED", "OBJECT", "OBJECT-COMPUTER", "OCCURS", "OF", "OFF", "OMITTED", "ON",
                  "OPEN", "OPTIONAL", "OR", "ORDER", "ORGANIZATION", "OTHER", "OUTPUT", "OVERFLOW",
                  "OVERRIDE", "PACKED-DECIMAL", "PADDING", "PAGE", "PAGE-COUNTER", "PASSWORD", "PERFORM",
                  "PF", "PH", "PIC", "PICTURE", "PLUS", "POINTER", "POSITION", "POSITIVE", "PRINTING",
                  "PROCEDURE", "PROCEDURE-POINTER", "PROCEDURES", "PROCEED", "PROCESSING", "PROGRAM",
                  "PROGRAM-ID", "PURGE", "QUEUE", "QUOTE", "QUOTES", "RANDOM", "RD", "READ", "READY", "RECEIVE",
                  "RECORD", "RECORDING", "RECORDS", "RECURSIVE", "REDEFINES", "REEL", "REFERENCE",
                  "REFERENCES", "RELATIVE", "RELEASE", "RELOAD", "REMAINDER", "REMOVAL", "RENAMES",
                  "REPLACE", "REPLACING", "REPORT", "REPORTING", "REPORTS", "REPOSITORY", "RERUN",
                  "RESERVE", "RESET", "RETURN", "RETURN-CODE", "RETURNING", "REVERSED", "REWIND",
                  "REWRITE", "RF", "RH", "RIGHT", "ROUNDED", "RUN", "SAME", "SD", "SEARCH", "SECTION",
                  "SECURITY", "SEGMENT", "SEGMENT-LIMIT", "SELECT", "SELF", "SEND", "SENTENCE",
                  "SEPARATE", "SEQUENCE", "SEQUENTIAL", "SERVICE", "SET", "SHIFT-IN", "SHIFT-OUT",
                  "SIGN", "SIZE", "SKIP1", "SKIP2", "SKIP3", "SORT", "SORT-CONTROL", "SORT-CORE-SIZE",
                  "SORT-FILE-SIZE", "SORT-MERGE", "SORT-MESSAGE", "SORT-MODE-SIZE", "SORT-RETURN",
                  "SOURCE", "SOURCE-COMPUTER", "SPACE", "SPACES", "SPECIAL-NAMES", "STANDARD",
                  "STANDARD-1", "STANDARD-2", "START", "STATUS", "STOP", "STRING", "SUB-QUEUE-1",
                  "SUB-QUEUE-2", "SUB-QUEUE-3", "SUBTRACT", "SUM", "SUPER", "SUPPRESS", "SYMBOLIC",
                  "SYNC", "SYNCHRONIZED", "TABLE", "TALLY", "TALLYING", "TAPE", "TERMINAL", "TERMINATE",
                  "TEST", "TEXT", "THAN", "THEN", "THROUGH", "THRU", "TIME", "TIMES", "TITLE", "TO",
                  "TOP", "TRACE", "TRAILING", "TRUE", "TYPE", "UNIT", "UNSTRING", "UNTIL", "UP",
                  "UPON", "USAGE", "USE", "USING", "VALUE", "VALUES", "VARYING", "WHEN", "WHEN-COMPILED",
                  "WITH", "WORDS", "WORKING-STORAGE", "WRITE", "WRITE-ONLY", "ZERO", "ZEROES", "ZEROS" ]
    
    static let BASIC = ["LET", "READ", "DATA", "PRINT", "GOTO", "IF", "THEN", "FOR", "TO",
                       "NEXT", "END", "STOP", "DEF", "GOSUB", "RETURN", "DIM", "REM", "RUN"]
    
    static let C = ["auto", "#include", "break", "case", "char", "const", "continue", "default",
                   "#define", "do", "double", "else", "enum", "extern", "float", "for", "free",
                   "func", "goto", "if", "int", "long", "main", "malloc", "printf", "register",
                   "return", "short", "signed", "sizeof", "static", "struct", "switch", "typedef",
                   "union", "unsigned", "void", "volatile", "while"]
    
    static let OPERATORS_C = ["+", "-", "*", "/", "%", "=", "==", ">", "<", "!", "&",
                            "&&", "|", "||", "(", ")", "{", "}", "?", ":", "->",
                            "[", "]", "(", ")", "{", "}", "{", "}"]
    
    static let OPERATORS_SQL = ["=", ">", "<", "(", ")", "{", "}", "{", "}"]
    
    static let SQL = ["ABORT", "ABORTSESSION", "ABS", "ABSOLUTE", "ACCESS", "ACCESSIBLE", "ACCESS_LOCK",
               "ACCOUNT", "ACOS", "ACOSH", "ACTION", "ADD", "ADD_MONTHS", "ADMIN", "AFTER",
               "AGGREGATE", "ALIAS", "ALL", "ALLOCATE", "ALLOW", "ALTER", "ALTERAND", "AMP",
               "ANALYSE", "ANALYZE", "AND", "ANSIDATE", "ANY", "ARE", "ARRAY", "ARRAY_AGG",
               "ARRAY_EXISTS", "ARRAY_MAX_CARDINALITY", "AS", "ASC", "ASENSITIVE", "ASIN",
               "ASINH", "ASSERTION", "ASSOCIATE", "ASUTIME", "ASYMMETRIC", "AT", "ATAN", "ATAN2",
               "ATANH", "ATOMIC", "AUDIT", "AUTHORIZATION", "AUX", "AUXILIARY", "AVE", "AVERAGE",
               "AVG", "BACKUP", "BEFORE", "BEGIN", "BEGIN_FRAME", "BEGIN_PARTITION", "BETWEEN",
               "BIGINT", "BINARY", "BIT", "BLOB", "BOOLEAN", "BOTH", "BREADTH", "BREAK",
               "BROWSE", "BT", "BUFFERPOOL", "BULK", "BUT", "BY", "BYTE", "BYTEINT", "BYTES",
               "CALL", "CALLED", "CAPTURE", "CARDINALITY", "CASCADE", "CASCADED", "CASE",
               "CASESPECIFIC", "CASE_N", "CAST", "CATALOG", "CCSID", "CD", "CEIL", "CEILING",
               "CHANGE", "CHAR", "CHAR2HEXINT", "CHARACTER", "CHARACTERS", "CHARACTER_LENGTH",
               "CHARS", "CHAR_LENGTH", "CHECK", "CHECKPOINT", "CLASS", "CLASSIFIER", "CLOB",
               "CLONE", "CLOSE", "CLUSTER", "CLUSTERED", "CM", "COALESCE", "COLLATE", "COLLATION",
               "COLLECT", "COLLECTION", "COLLID", "COLUMN", "COLUMN_VALUE", "COMMENT", "COMMIT",
               "COMPLETION", "COMPRESS", "COMPUTE", "CONCAT", "CONCURRENTLY", "CONDITION",
               "CONNECT", "CONNECTION", "CONSTRAINT", "CONSTRAINTS", "CONSTRUCTOR", "CONTAINS",
               "CONTAINSTABLE", "CONTENT", "CONTINUE", "CONVERT", "CONVERT_TABLE_HEADER",
               "COPY", "CORR", "CORRESPONDING", "COS", "COSH", "COUNT", "COVAR_POP", "COVAR_SAMP",
               "CREATE", "CROSS", "CS", "CSUM", "CT", "CUBE", "CUME_DIST", "CURRENT",
               "CURRENT_CATALOG", "CURRENT_DATE", "CURRENT_DEFAULT_TRANSFORM_GROUP",
               "CURRENT_LC_CTYPE", "CURRENT_PATH", "CURRENT_ROLE", "CURRENT_ROW", "CURRENT_SCHEMA",
               "CURRENT_SERVER", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_TIMEZONE",
               "CURRENT_TRANSFORM_GROUP_FOR_TYPE", "CURRENT_USER", "CURRVAL", "CURSOR", "CV",
               "CYCLE", "DATA", "DATABASE", "DATABASES", "DATABLOCKSIZE", "DATE", "DATEFORM",
               "DAY", "DAYS", "DAY_HOUR", "DAY_MICROSECOND", "DAY_MINUTE", "DAY_SECOND", "DBCC",
               "DBINFO", "DEALLOCATE", "DEC", "DECFLOAT", "DECIMAL", "DECLARE", "DEFAULT",
               "DEFERRABLE", "DEFERRED", "DEFINE", "DEGREES", "DEL", "DELAYED", "DELETE",
               "DENSE_RANK", "DENY", "DEPTH", "DEREF", "DESC", "DESCRIBE", "DESCRIPTOR",
               "DESTROY", "DESTRUCTOR", "DETERMINISTIC", "DIAGNOSTIC", "DIAGNOSTICS", "DICTIONARY",
               "DISABLE", "DISABLED", "DISALLOW", "DISCONNECT", "DISK", "DISTINCT", "DISTINCTROW",
               "DISTRIBUTED", "DIV", "DO", "DOCUMENT", "DOMAIN", "DOUBLE", "DROP", "DSSIZE",
               "DUAL", "DUMP", "DYNAMIC", "EACH", "ECHO", "EDITPROC", "ELEMENT", "ELSE", "ELSEIF",
               "EMPTY", "ENABLED", "ENCLOSED", "ENCODING", "ENCRYPTION", "END", "END-EXEC",
               "ENDING", "END_FRAME", "END_PARTITION", "EQ", "EQUALS", "ERASE", "ERRLVL", "ERROR",
               "ERRORFILES", "ERRORTABLES", "ESCAPE", "ESCAPED", "ET", "EVERY", "EXCEPT",
               "EXCEPTION", "EXCLUSIVE", "EXEC", "EXECUTE", "EXISTS", "EXIT", "EXP", "EXPLAIN",
               "EXTERNAL", "EXTRACT", "FALLBACK", "FALSE", "FASTEXPORT", "FENCED", "FETCH",
               "FIELDPROC", "FILE", "FILLFACTOR", "FILTER", "FINAL", "FIRST", "FIRST_VALUE",
               "FLOAT", "FLOAT4", "FLOAT8", "FLOOR", "FOR", "FORCE", "FOREIGN", "FORMAT", "FOUND",
               "FRAME_ROW", "FREE", "FREESPACE", "FREETEXT", "FREETEXTTABLE", "FREEZE", "FROM",
               "FULL", "FULLTEXT", "FUNCTION", "FUSION", "GE", "GENERAL", "GENERATED", "GET",
               "GIVE", "GLOBAL", "GO", "GOTO", "GRANT", "GRAPHIC", "GROUP", "GROUPING", "GROUPS",
               "GT", "HANDLER", "HASH", "HASHAMP", "HASHBAKAMP", "HASHBUCKET", "HASHROW",
               "HAVING", "HELP", "HIGH_PRIORITY", "HOLD", "HOLDLOCK", "HOST", "HOUR", "HOURS",
               "HOUR_MICROSECOND", "HOUR_MINUTE", "HOUR_SECOND", "IDENTIFIED", "IDENTITY",
               "IDENTITYCOL", "IDENTITY_INSERT", "IF", "IGNORE", "ILIKE", "IMMEDIATE", "IN",
               "INCLUSIVE", "INCONSISTENT", "INCREMENT", "INDEX", "INDICATOR", "INFILE", "INHERIT",
               "INITIAL", "INITIALIZE", "INITIALLY", "INITIATE", "INNER", "INOUT", "INPUT", "INS",
               "INSENSITIVE", "INSERT", "INSTEAD", "INT", "INT1", "INT2", "INT3", "INT4", "INT8",
               "INTEGER", "INTEGERDATE", "INTERSECT", "INTERSECTION", "INTERVAL", "INTO",
               "IO_AFTER_GTIDS", "IO_BEFORE_GTIDS", "IS", "ISNULL", "ISOBID", "ISOLATION",
               "ITERATE", "JAR", "JOIN", "JOURNAL", "JSON_ARRAY", "JSON_ARRAYAGG", "JSON_EXISTS",
               "JSON_OBJECT", "JSON_OBJECTAGG", "JSON_QUERY", "JSON_TABLE", "JSON_TABLE_PRIMITIVE",
               "JSON_VALUE", "KEEP", "KEY", "KEYS", "KILL", "KURTOSIS", "LABEL", "LAG", "LANGUAGE",
               "LARGE", "LAST", "LAST_VALUE", "LATERAL", "LC_CTYPE", "LE", "LEAD", "LEADING",
               "LEAVE", "LEFT", "LESS", "LEVEL", "LIKE", "LIKE_REGEX", "LIMIT", "LINEAR", "LINENO",
               "LINES", "LISTAGG", "LN", "LOAD", "LOADING", "LOCAL", "LOCALE", "LOCALTIME",
               "LOCALTIMESTAMP", "LOCATOR", "LOCATORS", "LOCK", "LOCKING", "LOCKMAX", "LOCKSIZE",
               "LOG", "LOG10", "LOGGING", "LOGON", "LONG", "LONGBLOB", "LONGTEXT", "LOOP",
               "LOWER", "LOW_PRIORITY", "LT", "MACRO", "MAINTAINED", "MAP", "MASTER_BIND",
               "MASTER_SSL_VERIFY_SERVER_CERT", "MATCH", "MATCHES", "MATCH_NUMBER",
               "MATCH_RECOGNIZE", "MATERIALIZED", "MAVG", "MAX", "MAXEXTENTS", "MAXIMUM",
               "MAXVALUE", "MCHARACTERS", "MDIFF", "MEDIUMBLOB", "MEDIUMINT", "MEDIUMTEXT",
               "MEMBER", "MERGE", "METHOD", "MICROSECOND", "MICROSECONDS", "MIDDLEINT", "MIN",
               "MINDEX", "MINIMUM", "MINUS", "MINUTE", "MINUTES", "MINUTE_MICROSECOND",
               "MINUTE_SECOND", "MLINREG", "MLOAD", "MLSLABEL", "MOD", "MODE", "MODIFIES",
               "MODIFY", "MODULE", "MONITOR", "MONRESOURCE", "MONSESSION", "MONTH", "MONTHS",
               "MSUBSTR", "MSUM", "MULTISET", "NAMED", "NAMES", "NATIONAL", "NATURAL", "NCHAR",
               "NCLOB", "NE", "NESTED_TABLE_ID", "NEW", "NEW_TABLE", "NEXT", "NEXTVAL", "NO",
               "NOAUDIT", "NOCHECK", "NOCOMPRESS", "NONCLUSTERED", "NONE", "NORMALIZE", "NOT",
               "NOTNULL", "NOWAIT", "NO_WRITE_TO_BINLOG", "NTH_VALUE", "NTILE", "NULL", "NULLIF",
               "NULLIFZERO", "NULLS", "NUMBER", "NUMERIC", "NUMPARTS", "OBID", "OBJECT",
               "OBJECTS", "OCCURRENCES_REGEX", "OCTET_LENGTH", "OF", "OFF", "OFFLINE", "OFFSET",
               "OFFSETS", "OLD", "OLD_TABLE", "OMIT", "ON", "ONE", "ONLINE", "ONLY", "OPEN",
               "OPENDATASOURCE", "OPENQUERY", "OPENROWSET", "OPENXML", "OPERATION", "OPTIMIZATION",
               "OPTIMIZE", "OPTIMIZER_COSTS", "OPTION", "OPTIONALLY", "OR", "ORDER", "ORDINALITY",
               "ORGANIZATION", "OUT", "OUTER", "OUTFILE", "OUTPUT", "OVER", "OVERLAPS", "OVERLAY",
               "OVERRIDE", "PACKAGE", "PAD", "PADDED", "PARAMETER", "PARAMETERS", "PART", "PARTIAL",
               "PARTITION", "PARTITIONED", "PARTITIONING", "PASSWORD", "PATH", "PATTERN", "PCTFREE",
               "PER", "PERCENT", "PERCENTILE_CONT", "PERCENTILE_DISC", "PERCENT_RANK", "PERIOD",
               "PERM", "PERMANENT", "PIECESIZE", "PIVOT", "PLACING", "PLAN", "PORTION", "POSITION",
               "POSITION_REGEX", "POSTFIX", "POWER", "PRECEDES", "PRECISION", "PREFIX", "PREORDER",
               "PREPARE", "PRESERVE", "PREVVAL", "PRIMARY", "PRINT", "PRIOR", "PRIQTY", "PRIVATE",
               "PRIVILEGES", "PROC", "PROCEDURE", "PROFILE", "PROGRAM", "PROPORTIONAL", "PROTECTION",
               "PSID", "PTF", "PUBLIC", "PURGE", "QUALIFIED", "QUALIFY", "QUANTILE", "QUERY",
               "QUERYNO", "RADIANS", "RAISERROR", "RANDOM", "RANGE", "RANGE_N", "RANK", "RAW",
               "READ", "READS", "READTEXT", "READ_WRITE", "REAL", "RECONFIGURE", "RECURSIVE",
               "REF", "REFERENCES", "REFERENCING", "REFRESH", "REGEXP", "REGR_AVGX", "REGR_AVGY",
               "REGR_COUNT", "REGR_INTERCEPT", "REGR_R2", "REGR_SLOPE", "REGR_SXX", "REGR_SXY",
               "REGR_SYY", "RELATIVE", "RELEASE", "RENAME", "REPEAT", "REPLACE", "REPLICATION",
               "REPOVERRIDE", "REQUEST", "REQUIRE", "RESIGNAL", "RESOURCE", "RESTART", "RESTORE",
               "RESTRICT", "RESULT", "RESULT_SET_LOCATOR", "RESUME", "RET", "RETRIEVE", "RETURN",
               "RETURNING", "RETURNS", "REVALIDATE", "REVERT", "REVOKE", "RIGHT", "RIGHTS",
               "RLIKE", "ROLE", "ROLLBACK", "ROLLFORWARD", "ROLLUP", "ROUND_CEILING", "ROUND_DOWN",
               "ROUND_FLOOR", "ROUND_HALF_DOWN", "ROUND_HALF_EVEN", "ROUND_HALF_UP", "ROUND_UP",
               "ROUTINE", "ROW", "ROWCOUNT", "ROWGUIDCOL", "ROWID", "ROWNUM", "ROWS", "ROWSET",
               "ROW_NUMBER", "RULE", "RUN", "RUNNING", "SAMPLE", "SAMPLEID", "SAVE", "SAVEPOINT",
               "SCHEMA", "SCHEMAS", "SCOPE", "SCRATCHPAD", "SCROLL", "SEARCH", "SECOND",
               "SECONDS", "SECOND_MICROSECOND", "SECQTY", "SECTION", "SECURITY", "SECURITYAUDIT",
               "SEEK", "SEL", "SELECT", "SEMANTICKEYPHRASETABLE", "SEMANTICSIMILARITYDETAILSTABLE",
               "SEMANTICSIMILARITYTABLE", "SENSITIVE", "SEPARATOR", "SEQUENCE", "SESSION",
               "SESSION_USER", "SET", "SETRESRATE", "SETS", "SETSESSRATE", "SETUSER", "SHARE",
               "SHOW", "SHUTDOWN", "SIGNAL", "SIMILAR", "SIMPLE", "SIN", "SINH", "SIZE", "SKEW",
               "SKIP", "SMALLINT", "SOME", "SOUNDEX", "SOURCE", "SPACE", "SPATIAL", "SPECIFIC",
               "SPECIFICTYPE", "SPOOL", "SQL", "SQLEXCEPTION", "SQLSTATE", "SQLTEXT", "SQLWARNING",
               "SQL_BIG_RESULT", "SQL_CALC_FOUND_ROWS", "SQL_SMALL_RESULT", "SQRT", "SS", "SSL",
               "STANDARD", "START", "STARTING", "STARTUP", "STATE", "STATEMENT", "STATIC",
               "STATISTICS", "STAY", "STDDEV_POP", "STDDEV_SAMP", "STEPINFO", "STOGROUP",
               "STORED", "STORES", "STRAIGHT_JOIN", "STRING_CS", "STRUCTURE", "STYLE",
               "SUBMULTISET", "SUBSCRIBER", "SUBSET", "SUBSTR", "SUBSTRING", "SUBSTRING_REGEX",
               "SUCCEEDS", "SUCCESSFUL", "SUM", "SUMMARY", "SUSPEND", "SYMMETRIC", "SYNONYM",
               "SYSDATE", "SYSTEM", "SYSTEM_TIME", "SYSTEM_USER", "SYSTIMESTAMP", "TABLE",
               "TABLESAMPLE", "TABLESPACE", "TAN", "TANH", "TBL_CS", "TEMPORARY", "TERMINATE",
               "TERMINATED", "TEXTSIZE", "THAN", "THEN", "THRESHOLD", "TIME", "TIMESTAMP",
               "TIMEZONE_HOUR", "TIMEZONE_MINUTE", "TINYBLOB", "TINYINT", "TINYTEXT", "TITLE",
               "TO", "TOP", "TRACE", "TRAILING", "TRAN", "TRANSACTION", "TRANSLATE",
               "TRANSLATE_CHK", "TRANSLATE_REGEX", "TRANSLATION", "TREAT", "TRIGGER", "TRIM",
               "TRIM_ARRAY", "TRUE", "TRUNCATE", "TRY_CONVERT", "TSEQUAL", "TYPE", "UC",
               "UESCAPE", "UID", "UNDEFINED", "UNDER", "UNDO", "UNION", "UNIQUE", "UNKNOWN",
               "UNLOCK", "UNNEST", "UNPIVOT", "UNSIGNED", "UNTIL", "UPD", "UPDATE", "UPDATETEXT",
               "UPPER", "UPPERCASE", "USAGE", "USE", "USER", "USING", "UTC_DATE", "UTC_TIME",
               "UTC_TIMESTAMP", "VALIDATE", "VALIDPROC", "VALUE", "VALUES", "VALUE_OF",
               "VARBINARY", "VARBYTE", "VARCHAR", "VARCHAR2", "VARCHARACTER", "VARGRAPHIC",
               "VARIABLE", "VARIADIC", "VARIANT", "VARYING", "VAR_POP", "VAR_SAMP", "VCAT",
               "VERBOSE", "VERSIONING", "VIEW", "VIRTUAL", "VOLATILE", "VOLUMES", "WAIT",
               "WAITFOR", "WHEN", "WHENEVER", "WHERE", "WHILE", "WIDTH_BUCKET", "WINDOW",
               "WITH", "WITHIN", "WITHIN_GROUP", "WITHOUT", "WLM", "WORK", "WRITE", "WRITETEXT",
               "XMLCAST", "XMLEXISTS", "XMLNAMESPACES", "XOR", "YEAR", "YEARS", "YEAR_MONTH",
               "ZEROFILL", "ZEROIFNULL", "ZONE"]
    
    static let HTML = ["a", "abbr", "acronym", "address", "applet", "area", "article", "aside",
                       "audio", "b", "base", "basefont", "bdo", "big", "blockquote", "body", "br",
                       "button", "canvas", "caption", "center", "cite", "code", "col", "colgroup",
                       "command", "datagrid", "datalist", "del", "details", "dfn", "dialog",
                       "dir", "div", "dl", "dt", "em", "embed", "eventsource", "fieldset", "figure",
                       "font", "footer", "form", "frame", "h1", "h2", "h3", "head", "header", "hgroup",
                       "hr", "html", "i", "iframe", "img", "input", "ins", "isindex", "kbd", "keygen",
                       "label", "legend", "li", "link", "map", "mark", "menu", "meta", "meter", "nav",
                       "noscript", "object", "ol", "optgroup", "option", "output", "p", "param", "pre",
                       "progress", "q", "rp", "rt", "ruby", "s", "samp", "script", "section",
                       "select", "small", "source", "span", "strike", "strong", "style", "sub",
                       "sup", "table", "tbody", "td", "textarea", "tfoot", "th", "thead", "time",
                       "title", "tr", "track", "u", "ul", "var", "video", "wbr"]
}
