// Copyright © 2021 Ni Fu. All rights reserved.

import Foundation

class ContentResource {
    
    // MARK: - Symbol
    
    static let CURRENCIES = ["$", "¢", "£", "¥", "؋", "৳", "₠", "૱", "௹", "฿"]
    
    static let EMOTICONS = [
        "ヾ(ﾟдﾟ)ﾉ゛", "ヽ(ﾟω､ﾟ)ﾉ", "ヾ(o´∀`o)ﾉ", "ヽ(･ω･´ﾒ)", "ヾ(●´∀`●)",
        "ヾ(=･ω･=)o", "ヽ(´Ａ`)ﾉ", "ヽ(´ｰ`)ﾉ", "ヽ(;´Д`)ﾉ", "ヾ(*ﾟω∩*)",
        "彡(-_-;)彡", "(((ﾟДﾟ)))", "ﾉ)ﾟДﾟ(ヽ", "つ;´･ω-)つ", "щ(`ω´щ)",
        "Ψ(`∀´)Ψ", "ΣΣ(ﾟдﾟlll)!", "Σ(ﾟДﾟ;≡;ﾟдﾟ)", "(;:ﾟ:ж:ﾟ:;)", "(｡-д-｡)ゞ",
        "(*´～`*)", "(´;ω;`)", "m(_ _)m", "《(;´Д`)》", "～(´ｰ`～)",
        "((((；ﾟДﾟ))))ｶﾞｸｶﾞｸﾌﾞﾙﾌﾞﾙ", "(((;°Д°;))))", "((.;ﾟ;:Д:;ﾟ;.))", "(*°ρ°*)", "_:(´ཀ`」 ∠):_",
        "_(:o 」∠)_", "(╯•ω•╰) I’m sorry…", "(´･_･人)", "ｳﾜｧｧ━━━｡ﾟ(ﾟ´Д｀ﾟ)ﾟ｡━━━ﾝ!!!!", "ｷﾀ━━━━(ﾟ∀ﾟ)━━━━!!",
        "きゃ━(;´༎ຶД༎ຶ`)━っっ!!!", ":;((っ°ө°ｃ));:", "ﾆﾔﾆﾔ(°∀° )ﾆﾔﾆﾔ", "(； ･`ω･´)ﾅﾝ…ﾀﾞﾄ!?", "∑( ◦д⊙)!!",
        "∑Σ( °∀°ﾉ)ﾉ", "ｱﾜ((ﾟﾟддﾟﾟ ))ﾜﾜ!!", "(・∀・)Good!!", "(´-﹏-`；)", "(๑･﹃ ･｀๑)ｼﾞｭﾙﾘ",
        "‹‹\\(´ω` )/››‹‹\\( 　´)/›› ‹‹\\( ´ω`)/››~♪", "(・(・(・(・д・)・)・)・) ﾌﾞﾝｼｰﾝ!!",
        "₍₍⁽⁽(ง ˙o˙)ว₎₎⁾⁾ ｳﾎﾎ ｳﾎ", "へ(ﾟ∀ﾟへ)ｵﾊﾞｹｪ～", "(((ง’ω’)و三 ง’ω’)ڡ≡ｼｭｯｼｭ", "─=≡Σ((( つ•̀ω•́)つ",
        "┏┗(´ิq´ิ)┓┛ｷｪｪｪｪｨｲｲｲｲｲ", "(‘ω’)三(ε: )三(.ω.)三( :3 )三(‘ω’)", "(`･ω･´)ゞﾋﾞｼｯ!!",
        "(^_^)", "ｳｲﾝｸ(^_-)-☆", "（⌒▽⌒", "＼(~o~)／", "(^0_0^)", "＼(^o^)／", "^O^ｱｰｰｰﾝ",
        "(^_^)!ﾋﾟﾝﾎﾟｰﾝ", "(^Ｑ^)ｱｰｰﾝ", "(⌒^⌒)ｂ", "p(^^)q", "ﾜｰｲ!(^Ｏ^)", "(^Q^)", "( ^)o(^ )",
        "o(^-^)o", "(^з^)-☆Chu!!", "(^-^)vｲｴｲ!", "(^o^)＼(^^ )ﾖｼﾖｼ", "(￣▽￣)Ｖ ", "ｲｴｰｲ    (#^_^#)",
        "(*^o^*)", "((*´∀))ｹﾗｹﾗ", "ﾎﾟﾘﾎﾟﾘf(^_^;", "ヾ(*´∀｀*)ﾉｷｬｯｷｬ", "(^^ゞﾃﾚﾃﾚ", "（*ゝ∀・*）",
        "ﾍﾍ（^^;", "(๑´ლ๑)ﾌﾌ♡", "ﾍ(･_･ﾍ)ｴﾍﾍ", "\\( ˆoˆ )/", "<(￣＾￣)>ｴｯﾍﾝ", "˖°٩( ‘ω’ )و", "٩(ˊᗜˋ*)و",
        "(o*ﾟｰﾟ)oﾜｸﾜｸ", "o(ˊ▽ˋ*)oﾜｸﾜｸ", "(*n’∀’)n ﾊﾞﾝｻﾞｰｲ", "(*´▽*)❀", "d( *＾ω＾*)pﾔｯﾀｰ!",
        "(*ﾟ▽ﾟ*)ワクワク", "*\\(^o^)/*", "\\( ˆoˆ )/", "(笑´ｗ｀)", "(￣ー￣)ﾆﾔﾘｯ", "\\( º∀º )/♪",
        "(*´∇*)", "(●´▽｀)ﾅﾊﾊ", "（￣ー＋￣）ニカッ！", "＼(^~^)／", "ヽ（●´3｀）ノ゛", "(￣￣▽￣￣)",
        "ｷﾀ━━━━(ﾟ∀ﾟ)━━━━!!", "ｷｬ━━━━(ﾟ∀ﾟ)━━━━!!", "(T-T)", "(ﾉ∇･､)ｸｽﾝ", "(T.T)", "（ｐ>□<ｑ*））",
        "｡ﾟ(Ｔ^Ｔ)ﾟ｡ﾟ", "(ノω=;)。。。", "(*6_6)o/~ﾊﾞｲﾊﾞｲ", "( ﾉД)ｼｸｼｸ…", "ヽ(≧Д≦)ノｳﾜｧｧﾝ!!",
        "(´ﾉω･｀*)ﾅｹﾙ－", "(´Д｀。)ｸﾞｽﾝ", "。゜(つω｀）゜。", "(´Ａ｀。)ｸﾞｽﾝ", "(´ﾉωﾉ)ﾒｿﾒｿ",
        "(´＿｀。)ｸﾞｽﾝ", "(PДq｡)", "・゜・(つД｀)・゜・", "(´；д；)ﾌﾞﾜｯ", "・゜゜・(/□＼*)・゜゜・わ～ん",
        "|ω；｀)ｳﾘｭﾘｭ｡｡", "( *´ｘ艸ｘ｀)ｳｳｯ..", "ﾄﾞﾊﾞｰｯ（┬┬＿┬┬）涙", "o(TヘTo) くぅ", "((((((((((((*ﾉﾉ) ﾋﾄﾞｲﾜｰｯ",
        "( T-T) ｳﾙｳﾙ", "号(┳Д┳)泣", "（ ´Д⊂ヽエーーン", "(´　ε　｀。･｡)ｸｽﾝ", "ｴｰﾝ!o(TヘT o)",
        "(´；ω；)ｳｯ", "（つд；*)ﾆｬﾝ…", "(　；∀；) ｶﾅｼｲﾅｰ", "(/へ＼*)ｳｩ、ﾋｯｸ", "｡ﾟ(ﾟ´⊃д･*)ﾟ｡+｡ｪ－ﾝ",
        "。ﾟ(ﾟﾉД｀ﾟ)ﾟ｡ｩﾜｰﾝｯ", "｡+ﾟ(ﾟつ皿ﾟ)ﾟ+｡ﾜｧｧﾝ!!", "｡･ﾟ(´pωq｀)ﾟ･｡", "（ΩДΩ）号泣", "（´・-・。）ｸｽﾝ",
        "。*゜(PД｀ﾟ)ﾟ｡わーん", "(´Δ´)・・・oｏｳﾜｰﾝ", "゜・（ｘ ω ｘ）・゜。", "(･∀･;)", "（´ω｀）ﾄﾎﾎ…",
        "( ˙▿˙ ; )", "(｡•́︿ •̀｡)", "(–;", "(^^;", "(..;)", "(･_･;", "(･_ ; )", "(..;)",
        "(‘Д｀)y-~~ｿｰﾅﾉ", "(-_-;", "（；´д｀）ノ ", "いや～    (^_^;A", "(_ _;)。。", "(^_^;ゞ",
        "0(T_T)0", "ｷﾞｸｯ(-_＾；)", "o(T^T)o", "（＾◇＾；", "(ﾟ_ﾟゝ", "＼(^^:;)…ﾏｱﾏｱ", "／(-_-)＼",
        "（ _ _ ）”", "(_-_)", "ε= (・c_,･｡A)ﾌｳｰ", "|(-_-)|ｷｺｴﾅｲ…", "(´∀｀; )", "(ﾟﾟ )( ﾟﾟ)ｷｮﾛｷｮﾛ",
        "ε- (-●_-o) ﾊﾌ-ﾝ…", "(･･ )( ･･)ｷｮﾛｷｮﾛ", "(¯―¯٥)", "（θ_θ;）ﾔﾚﾔﾚ", "ﾌｩ(o´Å｀)=з", "（￣～￣）ξ",
        "(⌒-⌒; )", "ε=（＠．＠；） ｳｯﾌﾟ", "ε=（×。×）ﾊｧ…。", "(^_^;", "(；・□・)ｴｴ..", "(°ﾛ°；)",
        "(ﾉc_,･;)ﾊｱ･･･", "(´)=3", "( ° 皿° ;; )", "(´-﹏-；)", "(￣Д)＝３", "ﾌｩ(o´Å｀)=з",
        "( ˘ω˘ ; )・・・。", "(((;´•ω•;)))", "(。・ε・。)", "(￣Д￣；)＝３ﾊｧ..", "(;Д;ﾟ；)",
        "(#･∀･)ﾑｶﾑｶ", "((“o(>ω<)o”))クヤシイー!!", "(*’へ’*)ぷんぷん", "｡･”(＞0＜)”･｡ﾝﾓｫ～",
        "（╬0∀0）=3ﾊｧ.", "q(-.-;)p?", "(-_- )凸", "(-_-#", "(-“- )", "(-_-ﾒ)", "ﾊﾟｰﾝﾁo(ﾟ◇ﾟ)○",
        "ﾁｪｯ(-｡ -; )", "ﾊﾞｺｯ(-_-;)=◎", "ﾁｪｯ!(-ε-)", "ﾊﾟﾝﾁo(_’)○", "ﾎﾞｶｯ＝○)゜o゜)☆", "(ﾟ.ﾟ ) ＼(-´)",
        "(._+)☆＼(-.-メ)ﾍﾟｼｯ", "(▼▼ﾒ)ﾅﾝﾀﾞﾄｫ", "(ﾟoﾟC=(__;ﾊﾞｷｯ", "（｀－´）ﾓｳ!", "o(･_･θキック",
        "(｀□´)ｺﾗｯ!", "ﾝﾓｫｰ!! o(*≧д≦)o″))", "★O=(_ )ﾊﾟﾝﾁ!", "(# ﾟДﾟ)つ〃∩ ｺﾞﾙｧ", "“o(▼皿▼メ;)o”ﾌﾟﾙﾌﾟﾙ",
        "o(｀･･_,´ﾒ)oﾌﾟﾝｽｶ!!", "((“o(ﾟ∩ﾟ*)ﾌﾟﾙﾌﾟﾙ･･", "ヽ(#｀_つ´)ﾉﾌﾟﾝｽｺ!!!!", "“o(￣‐￣*)　ﾌﾟﾙﾌﾟﾙ",
        "(´‐｀ ○）＼(○｀ε´○) ｺﾗ!ｺﾗ!", "| ｀Д´|ﾉこらぁ！", "o(怒･ｪ･´)ﾉ ｺﾘｬｰ!!", "((o(>皿<)o)) ｷｨｨｨ!!",
        "(。-ω´-)", "(－＂－怒)", "~l(≧∇≦)l~ ｳﾙｻｰｲ!", "(｡･ˇдˇ･｡)", "ε=ε=ε=(#・д・)/ ｺﾗｧｰ!!",
        "(# ﾟДﾟ)ｺﾞﾙｧ!!", "(｡・∀・)ﾖﾛｼｸ♪", "(m。_。)m ｵﾈｶﾞｲｼﾏｽ", "(^O^)/ｵｰｲ", "ﾊﾝｾｲ□＼(.. )",
        "(_o_)ｵｰｲ", "ﾘｮｳｶｲ!∠(^_^)", "あのうヽ(^_^;)", "ﾘｮｳｶｲ!(^-^ゝ", "ﾁｮｯﾄﾁｮｯﾄヾ(^_^", "ｻｱ…┐(-。-;)┌",
        "ﾊｰｲ(^o^)／", "ヽ(´ｰ)丿ﾌｳ", "♪(／°°)／￣ハィ", "ﾔｱ!＼(^_^ )", "(^-^)/~~~", "?( ^_^)／ﾔｱ!",
        "＼( ^ ^)/～〃ﾊﾞｲﾊﾞｲ", "＼(^_^ )", "ﾊﾞｲﾊﾞｲ(;_;)/~~~", "( ^_^)／ﾄﾞﾓﾄﾞﾓ", "　）))))‘‘）/~~~ ﾊﾞｲﾊﾞ～ｲ!",
        "m(_ _)mﾍﾟｺﾘ", "ｺﾞﾒﾝﾈ(・人・；)", "ｺﾞﾒﾝ<(_ _)>", "(ﾟ∇^*)ｵﾊﾖ♪", "(っ´Ι)っ { おはよう",
        "(o｡･･｡)o　ぉは～", "才ﾉヽ∋―_φ(ﾟ▽ﾟ*)♪", "(^-^*)/ｺﾝﾁｬ！", "*･ω･)ﾉ こん♪", "(ﾟ∇^*)ｺﾝﾆﾁﾜ",
        "。・∀・)ノ゛ｺﾝﾆﾁﾊ", "ヾ(´c_,｀*)ﾊﾞﾝﾜｧ～★", "(｡uωu)＜こんばんゎ", "( ^_^)／ｺﾝﾊﾞﾝﾊ", "(oﾟ▽ﾟ)oｺﾝﾊﾞﾝﾜ",
        "ﾏﾀｸﾙﾈ |･x･)ﾉ|Ю", "ε=┏(*`＞ω<)┛ｼﾞｬｧﾈ", "|´▽｀●)ﾉ |Ю 　| ｲｯﾃｷﾏｰｽ", "ｲｯﾃｷﾏｰｽ（っ・∀・）っ",
        "(・∀・)b OK!", "v(*’-^*)-☆ ok!", "（。＾Д＾。）／OK!", "(*｀д´)ｂ全然OK", "(o￣∇￣)ノそうだよ♪",
        "（●´∀｀）b そぅ☆", "d(ゝc_，・。)ｿｳｿｳ♪", "(｀・∀+´・)b そうだ！！", "(゜Д゜)ゞ了解!!",
        "d(´∀｀　)了解", "ﾗｼﾞｬ(*・ω・)ゞ⌒☆", "(*´∀｀)ゞﾗｼﾞｬ!", "(≧ω≦。)プププ", "ｸｽ(･m･*)ｸｽ",
        "(≧Σ≦)ぶっ！", "(_≧Д≦)ノ彡☆ばんばん", "ぷぷ(*￣m￣)o))", "( ´艸｀)ﾑﾌﾟﾌﾟ", "(*ﾟ▽ﾉﾟ*)おほほほ♪",
        "ﾜﾊﾊo(*^▽^*)o ｹﾗｹﾗ", "( ≧∇≦)ﾌﾞﾊﾊﾊﾊｯ", "∬≧ω≦):;*.’:;", "(´∇ﾉ｀*)ｵﾎﾎ♪", "(☆ﾟ∀ﾟ)ｱﾊﾊﾊ",
        "(　ﾟ,_ゝﾟ）ｯﾌﾟ", "((爆´∀｀笑))", "(ノ∀￣〃)ノ彡", "(≧w≦)ｳｼｼ", "(￣∇￣；) ﾊｯﾊｯﾊ…", "(p∇б★)",
        "(´0｀*)♪", "(*｀皿´*) ｳｼｼ", "(〃^∇^)o彡☆♪", "(-ι- ) クックック", "ヾ(@^▽^@)ノ",
        "ヽ(´▽｀)/爆笑", "(＾▽＾／)", "(≧ε≦●)ﾉ彡", "(^_^;)＼(‘_’) ｵｲｵｲ", "(･_･)ヾ(^o^;) ｵｲｵｲ",
        "(ﾟﾟ;)＼(–;)ｵｲｵｲ", "ヾ(–;)ぉぃぉぃ", "＼(- -;)ﾅﾝﾃﾞﾔﾈﾝ", "ヾ(~∇~;) ｺﾚｺﾚ", "(-_-;)ﾑｼﾑｼ",
        "ﾍ(..､ﾍ)☆＼(ﾟﾛﾟ )ﾅﾝﾃﾞﾔﾈﾝ!", "(ﾟ_｡)ｽﾞﾙｯ", "ヾ(-д-;)ぉぃぉぃ", "((((((;_ _)", "ヾ(･･ )ｫｨｫｨ",
        "(((((((^_^;)", "(;-o-)σｫｨｫｨ・・・", "(((((((;^^)", "Σ＼(￣ｰ￣;)ﾅﾝﾃﾞﾔﾈﾝ", "．．．．．．．．( ..)",
        "ﾅﾝﾃﾞﾔﾈﾝ!!(；＝＝)ノ", "（‥　）))))", "＼(￣ ￣*)ﾊﾞｼｯ", "(‘o’;)ｫｨｫｨｫｨ", "ヾ(~O~;) ｺﾘｬｺﾘｬ",
        "(・ε・。)ﾅﾝﾃﾞﾔﾈﾝ", ";･_･)_θ☆ﾋﾞｼｯ", "ゞ(￣∇￣;)ｽﾞﾙｯ", "ﾂｯｺﾐ(^o^)ノ☆/;^-^)ノ"
    ]
    
    // MARK: - Code
    
    static let COBOL = [
        "ACCEPT", "ACCESS", "ADD", "ADDRESS", "ADVANCING", "AFTER", "ALL", "ALPHABET",
        "ALPHABETIC", "ALPHABETIC-LOWER", "ALPHABETIC-UPPER", "ALPHANUMERIC",
        "ALPHANUMERIC-EDITED", "ALSO", "ALTER", "ALTERNATE", "AND", "ANY", "APPLY",
        "ARE", "AREA", "AREAS", "ASCENDING", "ASSIGN", "AT", "AUTHOR", "BASIS", "BEFORE",
        "BEGINNING", "BINARY", "BLANK", "BLOCK", "BOTTOM", "BY", "CALL", "CANCEL", "CBL",
        "CD", "CF", "CH", "CHARACTER", "CHARACTERS", "CLASS", "CLASS-ID", "CLOCK-UNITS",
        "CLOSE", "COBOL", "CODE", "CODE-SET", "COLLATING", "COLUMN", "COM-REG", "COMMA",
        "COMMON", "COMMUNICATION", "COMP", "COMP-1", "COMP-2", "COMP-3", "COMP-4", "COMP-5",
        "COMPUTATIONAL", "COMPUTATIONAL-1", "COMPUTATIONAL-2", "COMPUTATIONAL-3", "COMPUTATIONAL-4",
        "COMPUTATIONAL-5", "COMPUTE", "CONFIGURATION", "CONTAINS", "CONTENT", "CONTINUE",
        "CONTROL", "CONTROLS", "CONVERTING", "COPY", "CORR", "CORRESPONDING", "COUNT", "CURRENCY",
        "DATA", "DATE-COMPILED", "DATE-WRITTEN", "DAY", "DAY-OF-WEEK", "DBCS", "DE", "DEBUG-CONTENTS",
        "DEBUG-ITEM", "DEBUG-LINE", "DEBUG-NAME", "DEBUG-SUB-1", "DEBUG-SUB-2", "DEBUG-SUB-3",
        "DEBUGGING", "DECIMAL-POINT", "DECLARATIVES", "DELETE", "DELIMITED", "DELIMITER",
        "DEPENDING", "DESCENDING", "DESTINATION", "DETAIL", "DISPLAY", "DISPLAY-1", "DIVIDE",
        "DIVISION", "DOWN", "DUPLICATES", "DYNAMIC", "EGCS", "EGI", "EJECT", "ELSE", "EMI",
        "ENABLE", "END", "END-ADD", "END-CALL", "END-COMPUTE", "END-DELETE", "END-DIVIDE",
        "END-EVALUATE", "END-IF", "END-INVOKE", "END-MULTIPLY", "END-OF-PAGE", "END-PERFORM",
        "END-READ", "END-RECEIVE", "END-RETURN", "END-REWRITE", "END-SEARCH", "END-START",
        "END-STRING", "END-SUBTRACT", "END-UNSTRING", "END-WRITE", "ENDING", "ENTER", "ENTRY",
        "ENVIRONMENT", "EOP", "EQUAL", "ERROR", "ESI", "EVALUATE", "EVERY", "EXCEPTION",
        "EXIT", "EXTEND", "EXTERNAL", "FALSE", "FD", "FILE", "FILE-CONTROL", "FILLER",
        "FINAL", "FIRST", "FOOTING", "FOR", "FROM", "FUNCTION", "GENERATE", "GIVING",
        "GLOBAL", "GO", "GOBACK", "GREATER", "GROUP", "HEADING", "HIGH-VALUE", "HIGH-VALUES",
        "I-O", "I-O-CONTROL", "ID", "IDENTIFICATION", "IF", "IN", "INDEX", "INDEXED",
        "INDICATE", "INHERITS", "INITIAL", "INITIALIZE", "INITIATE", "INPUT", "INPUT-OUTPUT",
        "INSERT", "INSPECT", "INSTALLATION", "INTO", "INVALID", "INVOKE", "IS", "JUST", "JUSTIFIED",
        "KANJI KEY", "LABEL", "LAST", "LEADING", "LEFT", "LENGTH", "LESS", "LIMIT", "LIMITS",
        "LINAGE", "LINAGE-COUNTER", "LINE", "LINE-COUNTER", "LINES", "LINKAGE", "LOCAL-STORAGE",
        "LOCK", "LOW-VALUE", "LOW-VALUES", "MEMORY", "MERGE", "MESSAGE", "METACLASS", "METHOD",
        "METHOD-ID", "MODE", "MODULES", "MORE-LABELS", "MOVE", "MULTIPLE", "MULTIPLY", "NATIVE",
        "NATIVE_BINARY", "NEGATIVE", "NEXT", "NO", "NOT", "NULL", "NULLS", "NUMBER", "NUMERIC",
        "NUMERIC-EDITED", "OBJECT", "OBJECT-COMPUTER", "OCCURS", "OF", "OFF", "OMITTED", "ON",
        "OPEN", "OPTIONAL", "OR", "ORDER", "ORGANIZATION", "OTHER", "OUTPUT", "OVERFLOW",
        "OVERRIDE", "PACKED-DECIMAL", "PADDING", "PAGE", "PAGE-COUNTER", "PASSWORD", "PERFORM",
        "PF", "PH", "PIC", "PICTURE", "PLUS", "POINTER", "POSITION", "POSITIVE", "PRINTING",
        "PROCEDURE", "PROCEDURE-POINTER", "PROCEDURES", "PROCEED", "PROCESSING", "PROGRAM",
        "PROGRAM-ID", "PURGE", "QUEUE", "QUOTE", "QUOTES", "RANDOM", "RD", "READ", "READY", "RECEIVE",
        "RECORD", "RECORDING", "RECORDS", "RECURSIVE", "REDEFINES", "REEL", "REFERENCE",
        "REFERENCES", "RELATIVE", "RELEASE", "RELOAD", "REMAINDER", "REMOVAL", "RENAMES",
        "REPLACE", "REPLACING", "REPORT", "REPORTING", "REPORTS", "REPOSITORY", "RERUN",
        "RESERVE", "RESET", "RETURN", "RETURN-CODE", "RETURNING", "REVERSED", "REWIND",
        "REWRITE", "RF", "RH", "RIGHT", "ROUNDED", "RUN", "SAME", "SD", "SEARCH", "SECTION",
        "SECURITY", "SEGMENT", "SEGMENT-LIMIT", "SELECT", "SELF", "SEND", "SENTENCE",
        "SEPARATE", "SEQUENCE", "SEQUENTIAL", "SERVICE", "SET", "SHIFT-IN", "SHIFT-OUT",
        "SIGN", "SIZE", "SKIP1", "SKIP2", "SKIP3", "SORT", "SORT-CONTROL", "SORT-CORE-SIZE",
        "SORT-FILE-SIZE", "SORT-MERGE", "SORT-MESSAGE", "SORT-MODE-SIZE", "SORT-RETURN",
        "SOURCE", "SOURCE-COMPUTER", "SPACE", "SPACES", "SPECIAL-NAMES", "STANDARD",
        "STANDARD-1", "STANDARD-2", "START", "STATUS", "STOP", "STRING", "SUB-QUEUE-1",
        "SUB-QUEUE-2", "SUB-QUEUE-3", "SUBTRACT", "SUM", "SUPER", "SUPPRESS", "SYMBOLIC",
        "SYNC", "SYNCHRONIZED", "TABLE", "TALLY", "TALLYING", "TAPE", "TERMINAL", "TERMINATE",
        "TEST", "TEXT", "THAN", "THEN", "THROUGH", "THRU", "TIME", "TIMES", "TITLE", "TO",
        "TOP", "TRACE", "TRAILING", "TRUE", "TYPE", "UNIT", "UNSTRING", "UNTIL", "UP",
        "UPON", "USAGE", "USE", "USING", "VALUE", "VALUES", "VARYING", "WHEN", "WHEN-COMPILED",
        "WITH", "WORDS", "WORKING-STORAGE", "WRITE", "WRITE-ONLY", "ZERO", "ZEROES", "ZEROS"
    ]
    
    static let BASIC = [
        "LET", "READ", "DATA", "PRINT", "GOTO", "IF", "THEN", "FOR", "TO",
        "NEXT", "END", "STOP", "DEF", "GOSUB", "RETURN", "DIM", "REM", "RUN"
    ]
    
    static let C = [
        "auto", "#include", "break", "case", "char", "const", "continue", "default",
        "#define", "do", "double", "else", "enum", "extern", "float", "for", "free",
        "func", "goto", "if", "int", "long", "main", "malloc", "printf", "register",
        "return", "short", "signed", "sizeof", "static", "struct", "switch", "typedef",
        "union", "unsigned", "void", "volatile", "while"
    ]
    
    static let OPERATORS_C = [
        "+", "-", "*", "/", "%", "=", "==", ">", "<", "!", "&",
        "&&", "|", "||", "(", ")", "{", "}", "?", ":", "->",
        "[", "]", "(", ")", "{", "}", "{", "}"
    ]
    
    static let OPERATORS_SQL = ["=", ">", "<", "(", ")", "{", "}", "{", "}"]
    
    static let SQL = [
        "ABORT", "ABORTSESSION", "ABS", "ABSOLUTE", "ACCESS", "ACCESSIBLE", "ACCESS_LOCK",
        "ACCOUNT", "ACOS", "ACOSH", "ACTION", "ADD", "ADD_MONTHS", "ADMIN", "AFTER",
        "AGGREGATE", "ALIAS", "ALL", "ALLOCATE", "ALLOW", "ALTER", "ALTERAND", "AMP",
        "ANALYSE", "ANALYZE", "AND", "ANSIDATE", "ANY", "ARE", "ARRAY", "ARRAY_AGG",
        "ARRAY_EXISTS", "ARRAY_MAX_CARDINALITY", "AS", "ASC", "ASENSITIVE", "ASIN",
        "ASINH", "ASSERTION", "ASSOCIATE", "ASUTIME", "ASYMMETRIC", "AT", "ATAN", "ATAN2",
        "ATANH", "ATOMIC", "AUDIT", "AUTHORIZATION", "AUX", "AUXILIARY", "AVE", "AVERAGE",
        "AVG", "BACKUP", "BEFORE", "BEGIN", "BEGIN_FRAME", "BEGIN_PARTITION", "BETWEEN",
        "BIGINT", "BINARY", "BIT", "BLOB", "BOOLEAN", "BOTH", "BREADTH", "BREAK",
        "BROWSE", "BT", "BUFFERPOOL", "BULK", "BUT", "BY", "BYTE", "BYTEINT", "BYTES",
        "CALL", "CALLED", "CAPTURE", "CARDINALITY", "CASCADE", "CASCADED", "CASE",
        "CASESPECIFIC", "CASE_N", "CAST", "CATALOG", "CCSID", "CD", "CEIL", "CEILING",
        "CHANGE", "CHAR", "CHAR2HEXINT", "CHARACTER", "CHARACTERS", "CHARACTER_LENGTH",
        "CHARS", "CHAR_LENGTH", "CHECK", "CHECKPOINT", "CLASS", "CLASSIFIER", "CLOB",
        "CLONE", "CLOSE", "CLUSTER", "CLUSTERED", "CM", "COALESCE", "COLLATE", "COLLATION",
        "COLLECT", "COLLECTION", "COLLID", "COLUMN", "COLUMN_VALUE", "COMMENT", "COMMIT",
        "COMPLETION", "COMPRESS", "COMPUTE", "CONCAT", "CONCURRENTLY", "CONDITION",
        "CONNECT", "CONNECTION", "CONSTRAINT", "CONSTRAINTS", "CONSTRUCTOR", "CONTAINS",
        "CONTAINSTABLE", "CONTENT", "CONTINUE", "CONVERT", "CONVERT_TABLE_HEADER",
        "COPY", "CORR", "CORRESPONDING", "COS", "COSH", "COUNT", "COVAR_POP", "COVAR_SAMP",
        "CREATE", "CROSS", "CS", "CSUM", "CT", "CUBE", "CUME_DIST", "CURRENT",
        "CURRENT_CATALOG", "CURRENT_DATE", "CURRENT_DEFAULT_TRANSFORM_GROUP",
        "CURRENT_LC_CTYPE", "CURRENT_PATH", "CURRENT_ROLE", "CURRENT_ROW", "CURRENT_SCHEMA",
        "CURRENT_SERVER", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_TIMEZONE",
        "CURRENT_TRANSFORM_GROUP_FOR_TYPE", "CURRENT_USER", "CURRVAL", "CURSOR", "CV",
        "CYCLE", "DATA", "DATABASE", "DATABASES", "DATABLOCKSIZE", "DATE", "DATEFORM",
        "DAY", "DAYS", "DAY_HOUR", "DAY_MICROSECOND", "DAY_MINUTE", "DAY_SECOND", "DBCC",
        "DBINFO", "DEALLOCATE", "DEC", "DECFLOAT", "DECIMAL", "DECLARE", "DEFAULT",
        "DEFERRABLE", "DEFERRED", "DEFINE", "DEGREES", "DEL", "DELAYED", "DELETE",
        "DENSE_RANK", "DENY", "DEPTH", "DEREF", "DESC", "DESCRIBE", "DESCRIPTOR",
        "DESTROY", "DESTRUCTOR", "DETERMINISTIC", "DIAGNOSTIC", "DIAGNOSTICS", "DICTIONARY",
        "DISABLE", "DISABLED", "DISALLOW", "DISCONNECT", "DISK", "DISTINCT", "DISTINCTROW",
        "DISTRIBUTED", "DIV", "DO", "DOCUMENT", "DOMAIN", "DOUBLE", "DROP", "DSSIZE",
        "DUAL", "DUMP", "DYNAMIC", "EACH", "ECHO", "EDITPROC", "ELEMENT", "ELSE", "ELSEIF",
        "EMPTY", "ENABLED", "ENCLOSED", "ENCODING", "ENCRYPTION", "END", "END-EXEC",
        "ENDING", "END_FRAME", "END_PARTITION", "EQ", "EQUALS", "ERASE", "ERRLVL", "ERROR",
        "ERRORFILES", "ERRORTABLES", "ESCAPE", "ESCAPED", "ET", "EVERY", "EXCEPT",
        "EXCEPTION", "EXCLUSIVE", "EXEC", "EXECUTE", "EXISTS", "EXIT", "EXP", "EXPLAIN",
        "EXTERNAL", "EXTRACT", "FALLBACK", "FALSE", "FASTEXPORT", "FENCED", "FETCH",
        "FIELDPROC", "FILE", "FILLFACTOR", "FILTER", "FINAL", "FIRST", "FIRST_VALUE",
        "FLOAT", "FLOAT4", "FLOAT8", "FLOOR", "FOR", "FORCE", "FOREIGN", "FORMAT", "FOUND",
        "FRAME_ROW", "FREE", "FREESPACE", "FREETEXT", "FREETEXTTABLE", "FREEZE", "FROM",
        "FULL", "FULLTEXT", "FUNCTION", "FUSION", "GE", "GENERAL", "GENERATED", "GET",
        "GIVE", "GLOBAL", "GO", "GOTO", "GRANT", "GRAPHIC", "GROUP", "GROUPING", "GROUPS",
        "GT", "HANDLER", "HASH", "HASHAMP", "HASHBAKAMP", "HASHBUCKET", "HASHROW",
        "HAVING", "HELP", "HIGH_PRIORITY", "HOLD", "HOLDLOCK", "HOST", "HOUR", "HOURS",
        "HOUR_MICROSECOND", "HOUR_MINUTE", "HOUR_SECOND", "IDENTIFIED", "IDENTITY",
        "IDENTITYCOL", "IDENTITY_INSERT", "IF", "IGNORE", "ILIKE", "IMMEDIATE", "IN",
        "INCLUSIVE", "INCONSISTENT", "INCREMENT", "INDEX", "INDICATOR", "INFILE", "INHERIT",
        "INITIAL", "INITIALIZE", "INITIALLY", "INITIATE", "INNER", "INOUT", "INPUT", "INS",
        "INSENSITIVE", "INSERT", "INSTEAD", "INT", "INT1", "INT2", "INT3", "INT4", "INT8",
        "INTEGER", "INTEGERDATE", "INTERSECT", "INTERSECTION", "INTERVAL", "INTO",
        "IO_AFTER_GTIDS", "IO_BEFORE_GTIDS", "IS", "ISNULL", "ISOBID", "ISOLATION",
        "ITERATE", "JAR", "JOIN", "JOURNAL", "JSON_ARRAY", "JSON_ARRAYAGG", "JSON_EXISTS",
        "JSON_OBJECT", "JSON_OBJECTAGG", "JSON_QUERY", "JSON_TABLE", "JSON_TABLE_PRIMITIVE",
        "JSON_VALUE", "KEEP", "KEY", "KEYS", "KILL", "KURTOSIS", "LABEL", "LAG", "LANGUAGE",
        "LARGE", "LAST", "LAST_VALUE", "LATERAL", "LC_CTYPE", "LE", "LEAD", "LEADING",
        "LEAVE", "LEFT", "LESS", "LEVEL", "LIKE", "LIKE_REGEX", "LIMIT", "LINEAR", "LINENO",
        "LINES", "LISTAGG", "LN", "LOAD", "LOADING", "LOCAL", "LOCALE", "LOCALTIME",
        "LOCALTIMESTAMP", "LOCATOR", "LOCATORS", "LOCK", "LOCKING", "LOCKMAX", "LOCKSIZE",
        "LOG", "LOG10", "LOGGING", "LOGON", "LONG", "LONGBLOB", "LONGTEXT", "LOOP",
        "LOWER", "LOW_PRIORITY", "LT", "MACRO", "MAINTAINED", "MAP", "MASTER_BIND",
        "MASTER_SSL_VERIFY_SERVER_CERT", "MATCH", "MATCHES", "MATCH_NUMBER",
        "MATCH_RECOGNIZE", "MATERIALIZED", "MAVG", "MAX", "MAXEXTENTS", "MAXIMUM",
        "MAXVALUE", "MCHARACTERS", "MDIFF", "MEDIUMBLOB", "MEDIUMINT", "MEDIUMTEXT",
        "MEMBER", "MERGE", "METHOD", "MICROSECOND", "MICROSECONDS", "MIDDLEINT", "MIN",
        "MINDEX", "MINIMUM", "MINUS", "MINUTE", "MINUTES", "MINUTE_MICROSECOND",
        "MINUTE_SECOND", "MLINREG", "MLOAD", "MLSLABEL", "MOD", "MODE", "MODIFIES",
        "MODIFY", "MODULE", "MONITOR", "MONRESOURCE", "MONSESSION", "MONTH", "MONTHS",
        "MSUBSTR", "MSUM", "MULTISET", "NAMED", "NAMES", "NATIONAL", "NATURAL", "NCHAR",
        "NCLOB", "NE", "NESTED_TABLE_ID", "NEW", "NEW_TABLE", "NEXT", "NEXTVAL", "NO",
        "NOAUDIT", "NOCHECK", "NOCOMPRESS", "NONCLUSTERED", "NONE", "NORMALIZE", "NOT",
        "NOTNULL", "NOWAIT", "NO_WRITE_TO_BINLOG", "NTH_VALUE", "NTILE", "NULL", "NULLIF",
        "NULLIFZERO", "NULLS", "NUMBER", "NUMERIC", "NUMPARTS", "OBID", "OBJECT",
        "OBJECTS", "OCCURRENCES_REGEX", "OCTET_LENGTH", "OF", "OFF", "OFFLINE", "OFFSET",
        "OFFSETS", "OLD", "OLD_TABLE", "OMIT", "ON", "ONE", "ONLINE", "ONLY", "OPEN",
        "OPENDATASOURCE", "OPENQUERY", "OPENROWSET", "OPENXML", "OPERATION", "OPTIMIZATION",
        "OPTIMIZE", "OPTIMIZER_COSTS", "OPTION", "OPTIONALLY", "OR", "ORDER", "ORDINALITY",
        "ORGANIZATION", "OUT", "OUTER", "OUTFILE", "OUTPUT", "OVER", "OVERLAPS", "OVERLAY",
        "OVERRIDE", "PACKAGE", "PAD", "PADDED", "PARAMETER", "PARAMETERS", "PART", "PARTIAL",
        "PARTITION", "PARTITIONED", "PARTITIONING", "PASSWORD", "PATH", "PATTERN", "PCTFREE",
        "PER", "PERCENT", "PERCENTILE_CONT", "PERCENTILE_DISC", "PERCENT_RANK", "PERIOD",
        "PERM", "PERMANENT", "PIECESIZE", "PIVOT", "PLACING", "PLAN", "PORTION", "POSITION",
        "POSITION_REGEX", "POSTFIX", "POWER", "PRECEDES", "PRECISION", "PREFIX", "PREORDER",
        "PREPARE", "PRESERVE", "PREVVAL", "PRIMARY", "PRINT", "PRIOR", "PRIQTY", "PRIVATE",
        "PRIVILEGES", "PROC", "PROCEDURE", "PROFILE", "PROGRAM", "PROPORTIONAL", "PROTECTION",
        "PSID", "PTF", "PUBLIC", "PURGE", "QUALIFIED", "QUALIFY", "QUANTILE", "QUERY",
        "QUERYNO", "RADIANS", "RAISERROR", "RANDOM", "RANGE", "RANGE_N", "RANK", "RAW",
        "READ", "READS", "READTEXT", "READ_WRITE", "REAL", "RECONFIGURE", "RECURSIVE",
        "REF", "REFERENCES", "REFERENCING", "REFRESH", "REGEXP", "REGR_AVGX", "REGR_AVGY",
        "REGR_COUNT", "REGR_INTERCEPT", "REGR_R2", "REGR_SLOPE", "REGR_SXX", "REGR_SXY",
        "REGR_SYY", "RELATIVE", "RELEASE", "RENAME", "REPEAT", "REPLACE", "REPLICATION",
        "REPOVERRIDE", "REQUEST", "REQUIRE", "RESIGNAL", "RESOURCE", "RESTART", "RESTORE",
        "RESTRICT", "RESULT", "RESULT_SET_LOCATOR", "RESUME", "RET", "RETRIEVE", "RETURN",
        "RETURNING", "RETURNS", "REVALIDATE", "REVERT", "REVOKE", "RIGHT", "RIGHTS",
        "RLIKE", "ROLE", "ROLLBACK", "ROLLFORWARD", "ROLLUP", "ROUND_CEILING", "ROUND_DOWN",
        "ROUND_FLOOR", "ROUND_HALF_DOWN", "ROUND_HALF_EVEN", "ROUND_HALF_UP", "ROUND_UP",
        "ROUTINE", "ROW", "ROWCOUNT", "ROWGUIDCOL", "ROWID", "ROWNUM", "ROWS", "ROWSET",
        "ROW_NUMBER", "RULE", "RUN", "RUNNING", "SAMPLE", "SAMPLEID", "SAVE", "SAVEPOINT",
        "SCHEMA", "SCHEMAS", "SCOPE", "SCRATCHPAD", "SCROLL", "SEARCH", "SECOND",
        "SECONDS", "SECOND_MICROSECOND", "SECQTY", "SECTION", "SECURITY", "SECURITYAUDIT",
        "SEEK", "SEL", "SELECT", "SEMANTICKEYPHRASETABLE", "SEMANTICSIMILARITYDETAILSTABLE",
        "SEMANTICSIMILARITYTABLE", "SENSITIVE", "SEPARATOR", "SEQUENCE", "SESSION",
        "SESSION_USER", "SET", "SETRESRATE", "SETS", "SETSESSRATE", "SETUSER", "SHARE",
        "SHOW", "SHUTDOWN", "SIGNAL", "SIMILAR", "SIMPLE", "SIN", "SINH", "SIZE", "SKEW",
        "SKIP", "SMALLINT", "SOME", "SOUNDEX", "SOURCE", "SPACE", "SPATIAL", "SPECIFIC",
        "SPECIFICTYPE", "SPOOL", "SQL", "SQLEXCEPTION", "SQLSTATE", "SQLTEXT", "SQLWARNING",
        "SQL_BIG_RESULT", "SQL_CALC_FOUND_ROWS", "SQL_SMALL_RESULT", "SQRT", "SS", "SSL",
        "STANDARD", "START", "STARTING", "STARTUP", "STATE", "STATEMENT", "STATIC",
        "STATISTICS", "STAY", "STDDEV_POP", "STDDEV_SAMP", "STEPINFO", "STOGROUP",
        "STORED", "STORES", "STRAIGHT_JOIN", "STRING_CS", "STRUCTURE", "STYLE",
        "SUBMULTISET", "SUBSCRIBER", "SUBSET", "SUBSTR", "SUBSTRING", "SUBSTRING_REGEX",
        "SUCCEEDS", "SUCCESSFUL", "SUM", "SUMMARY", "SUSPEND", "SYMMETRIC", "SYNONYM",
        "SYSDATE", "SYSTEM", "SYSTEM_TIME", "SYSTEM_USER", "SYSTIMESTAMP", "TABLE",
        "TABLESAMPLE", "TABLESPACE", "TAN", "TANH", "TBL_CS", "TEMPORARY", "TERMINATE",
        "TERMINATED", "TEXTSIZE", "THAN", "THEN", "THRESHOLD", "TIME", "TIMESTAMP",
        "TIMEZONE_HOUR", "TIMEZONE_MINUTE", "TINYBLOB", "TINYINT", "TINYTEXT", "TITLE",
        "TO", "TOP", "TRACE", "TRAILING", "TRAN", "TRANSACTION", "TRANSLATE",
        "TRANSLATE_CHK", "TRANSLATE_REGEX", "TRANSLATION", "TREAT", "TRIGGER", "TRIM",
        "TRIM_ARRAY", "TRUE", "TRUNCATE", "TRY_CONVERT", "TSEQUAL", "TYPE", "UC",
        "UESCAPE", "UID", "UNDEFINED", "UNDER", "UNDO", "UNION", "UNIQUE", "UNKNOWN",
        "UNLOCK", "UNNEST", "UNPIVOT", "UNSIGNED", "UNTIL", "UPD", "UPDATE", "UPDATETEXT",
        "UPPER", "UPPERCASE", "USAGE", "USE", "USER", "USING", "UTC_DATE", "UTC_TIME",
        "UTC_TIMESTAMP", "VALIDATE", "VALIDPROC", "VALUE", "VALUES", "VALUE_OF",
        "VARBINARY", "VARBYTE", "VARCHAR", "VARCHAR2", "VARCHARACTER", "VARGRAPHIC",
        "VARIABLE", "VARIADIC", "VARIANT", "VARYING", "VAR_POP", "VAR_SAMP", "VCAT",
        "VERBOSE", "VERSIONING", "VIEW", "VIRTUAL", "VOLATILE", "VOLUMES", "WAIT",
        "WAITFOR", "WHEN", "WHENEVER", "WHERE", "WHILE", "WIDTH_BUCKET", "WINDOW",
        "WITH", "WITHIN", "WITHIN_GROUP", "WITHOUT", "WLM", "WORK", "WRITE", "WRITETEXT",
        "XMLCAST", "XMLEXISTS", "XMLNAMESPACES", "XOR", "YEAR", "YEARS", "YEAR_MONTH",
        "ZEROFILL", "ZEROIFNULL", "ZONE"
    ]
    
    static let HTML = [
        "a", "abbr", "acronym", "address", "applet", "area", "article", "aside",
        "audio", "b", "base", "basefont", "bdo", "big", "blockquote", "body", "br",
        "button", "canvas", "caption", "center", "cite", "code", "col", "colgroup",
        "command", "datagrid", "datalist", "del", "details", "dfn", "dialog",
        "dir", "div", "dl", "dt", "em", "embed", "eventsource", "fieldset", "figure",
        "font", "footer", "form", "frame", "h1", "h2", "h3", "head", "header", "hgroup",
        "hr", "html", "i", "iframe", "img", "input", "ins", "isindex", "kbd", "keygen",
        "label", "legend", "li", "link", "map", "mark", "menu", "meta", "meter", "nav",
        "noscript", "object", "ol", "optgroup", "option", "output", "p", "param", "pre",
        "progress", "q", "rp", "rt", "ruby", "s", "samp", "script", "section",
        "select", "small", "source", "span", "strike", "strong", "style", "sub",
        "sup", "table", "tbody", "td", "textarea", "tfoot", "th", "thead", "time",
        "title", "tr", "track", "u", "ul", "var", "video", "wbr"
    ]
    
    // MARK: - Language
    
    static let ENGLISH = [
        "as", "I", "his", "that", "he", "was", "for", "on", "are", "with", "they",
        "be", "at", "one", "have", "this", "from", "by", "hot", "word", "but", "what",
        "some", "is", "it", "you", "or", "had", "the", "of", "to", "and", "a", "in",
        "we", "can", "out", "other", "were", "which", "do", "their", "time", "if",
        "will", "how", "said", "an", "each", "tell", "does", "set", "three", "want",
        "air", "well", "also", "play", "small", "end", "put", "home", "read", "hand",
        "port", "large", "spell", "add", "even", "land", "here", "must", "big", "high",
        "such", "follow", "act", "why", "ask", "men", "change", "went", "light", "kind",
        "off", "need", "house", "picture", "try", "us", "again", "animal", "point",
        "mother", "world", "near", "build", "self", "earth", "father", "any", "new",
        "work", "part", "take", "get", "place", "made", "live", "where", "after",
        "back", "little", "only", "round", "man", "year", "came", "show", "every",
        "good", "me", "give", "our", "under", "name", "very", "through", "just",
        "form", "sentence", "great", "think", "say", "help", "low", "line", "differ",
        "turn", "cause", "much", "mean", "before", "move", "right", "boy", "old",
        "too", "same", "she", "all", "there", "when", "up", "use", "your", "way",
        "about", "many", "then", "them", "write", "would", "like", "so", "these",
        "her", "long", "make", "thing", "see", "him", "two", "has", "look", "more",
        "day", "could", "go", "come", "did", "number", "sound", "no", "most", "people",
        "my", "over", "know", "water", "than", "call", "first", "who", "may", "down",
        "side", "been", "now", "find", "head", "stand", "own", "page", "should",
        "country", "found", "answer", "school", "grow", "study", "still", "learn",
        "plant", "cover", "food", "sun", "four", "between", "state", "keep", "eye",
        "never", "last", "let", "thought", "city", "tree", "cross", "farm", "hard",
        "start", "might", "story", "saw", "far", "sea", "draw", "left", "late", "run",
        "don’t", "while", "press", "close", "night", "real", "life", "few", "north",
        "book", "carry", "took", "science", "eat", "room", "friend", "began", "idea",
        "fish", "mountain", "stop", "once", "base", "hear", "horse", "cut", "sure",
        "watch", "color", "face", "wood", "main", "open", "seem", "together", "next",
        "white", "children", "begin", "got", "walk", "example", "ease", "paper",
        "group", "always", "music", "those", "both", "mark", "often", "letter",
        "until", "mile", "river", "car", "feet", "care", "second", "enough", "plain",
        "girl", "usual", "young", "ready", "above", "ever", "red", "list", "though",
        "feel", "talk", "bird", "soon", "body", "dog", "family", "direct", "pose",
        "leave", "song", "measure", "door", "product", "black", "short", "numeral",
        "class", "wind", "question", "happen", "complete", "ship", "area", "half",
        "rock", "order", "fire", "south", "problem", "piece", "told", "knew", "pass",
        "since", "top", "whole", "king", "street", "inch", "multiply", "nothing",
        "course", "stay", "wheel", "full", "force", "blue", "object", "decide",
        "surface", "deep", "moon", "island", "foot", "system", "busy", "test",
        "record", "boat", "common", "gold", "possible", "plane", "stead", "dry",
        "wonder", "laugh", "thousand", "ago", "ran", "check", "game", "shape",
        "equate", "hot", "miss", "brought", "heat", "snow", "tire", "bring", "yes",
        "distant", "fill", "east", "paint", "language", "among", "unit", "power",
        "town", "fine", "certain", "fly", "fall", "lead", "cry", "dark", "machine",
        "note", "wait", "plan", "figure", "star", "box", "noun", "field", "rest",
        "correct", "able", "pound", "done", "beauty", "drive", "stood", "contain",
        "front", "teach", "week", "final", "gave", "green", "oh", "quick", "develop",
        "ocean", "warm", "free", "minute", "strong", "special", "mind", "behind",
        "clear", "tail", "produce", "fact", "space", "heard", "best", "hour", "better",
        "true", "during", "hundred", "five", "remember", "step", "early", "hold",
        "west", "ground", "interest", "reach", "fast", "verb", "sing", "listen",
        "six", "table", "travel", "less", "morning", "ten", "simple", "several",
        "vowel", "toward", "war", "lay", "against", "pattern", "slow", "center",
        "love", "person", "money", "serve", "appear", "road", "map", "rain", "rule",
        "govern", "pull", "cold", "notice", "voice", "energy", "hunt", "probable",
        "bed", "brother", "egg", "ride", "cell", "believe", "perhaps", "pick", "sudden",
        "count", "square", "reason", "length", "represent", "art", "subject", "region",
        "size", "vary", "settle", "speak", "weight", "general", "ice", "matter",
        "circle", "pair", "include", "divide", "syllable", "felt", "grand", "ball",
        "yet", "wave", "drop", "heart", "am", "present", "heavy", "dance", "engine",
        "position", "arm", "wide", "sail", "material", "fraction", "forest", "sit",
        "race", "window", "store", "summer", "train", "sleep", "prove", "lone", "leg",
        "exercise", "wall", "catch", "mount", "wish", "sky", "board", "joy", "winter",
        "sat", "written", "wild", "instrument", "kept", "glass", "grass", "cow", "job",
        "edge", "sign", "visit", "past", "soft", "fun", "bright", "gas", "weather",
        "month", "million", "bear", "finish", "happy", "hope", "flower", "clothe",
        "strange", "gone", "trade", "melody", "trip", "office", "receive", "row",
        "mouth", "exact", "symbol", "die", "least", "trouble", "shout", "except",
        "wrote", "seed", "tone", "join", "suggest", "clean", "break", "lady", "yard",
        "rise", "bad", "blow", "oil", "blood", "touch", "grew", "cent", "mix",
        "team", "wire", "cost", "lost", "brown", "wear", "garden", "equal", "sent",
        "choose", "fell", "fit", "flow", "fair", "bank", "collect", "save", "control",
        "decimal", "ear", "else", "quite", "broke", "case", "middle", "kill", "son",
        "lake", "moment", "scale", "loud", "spring", "observe", "child", "straight",
        "consonant", "nation", "dictionary", "milk", "speed", "method", "organ", "pay",
        "age", "section", "dress", "cloud", "surprise", "quiet", "stone", "tiny",
        "climb", "cool", "design", "poor", "lot", "experiment", "bottom", "key", "iron",
        "single", "stick", "flat", "twenty", "skin", "smile", "crease", "hole", "jump",
        "baby", "eight", "village", "meet", "root", "buy", "raise", "solve", "metal",
        "whether", "push", "seven", "paragraph", "third", "shall", "held", "hair",
        "describe", "cook", "floor", "either", "result", "burn", "hill", "safe", "cat",
        "century", "consider", "type", "law", "bit", "coast", "copy", "phrase", "silent",
        "tall", "sand", "soil", "roll", "temperature", "finger", "industry", "value",
        "fight", "lie", "beat", "excite", "natural", "view", "sense", "capital",
        "won’t", "chair", "danger", "fruit", "rich", "thick", "soldier", "process",
        "operate", "practice", "separate", "difficult", "doctor", "please", "protect",
        "noon", "crop", "modern", "element", "hit", "student", "corner", "party",
        "supply", "whose", "locate", "ring", "character", "insect", "caught", "period",
        "indicate", "radio", "spoke", "atom", "human", "history", "effect", "electric",
        "expect", "bone", "rail", "imagine", "provide", "agree", "thus", "gentle",
        "woman", "captain", "guess", "necessary", "sharp", "wing", "create", "neighbor",
        "wash", "bat", "rather", "crowd", "corn", "compare", "poem", "string", "bell",
        "depend", "meat", "rub", "tube", "famous", "dollar", "stream", "fear", "sight",
        "thin", "triangle", "planet", "hurry", "chief", "colony", "clock", "mine",
        "tie", "enter", "major", "fresh", "search", "send", "yellow", "gun", "allow",
        "print", "dead", "spot", "desert", "suit", "current", "lift", "rose", "arrive",
        "master", "track", "parent", "shore", "division", "sheet", "substance", "favor",
        "connect", "post", "spend", "chord", "fat", "glad", "original", "share",
        "station", "dad", "bread", "charge", "proper", "bar", "offer", "segment",
        "slave", "duck", "instant", "market", "degree", "populate", "chick", "dear",
        "enemy", "reply", "drink", "occur", "support", "speech", "nature", "range",
        "steam", "motion", "path", "liquid", "log", "meant", "quotient", "teeth",
        "shell", "neck", "oxygen", "sugar", "death", "pretty", "skill", "women",
        "season", "solution", "magnet", "silver", "thank", "branch", "match", "suffix",
        "especially", "fig", "afraid", "huge", "sister", "steel", "discuss", "forward",
        "similar", "guide", "experience", "score", "apple", "bought", "led", "pitch",
        "coat", "mass", "card", "band", "rope", "slip", "win", "dream", "evening",
        "condition", "feed", "tool", "total", "basic", "smell", "valley", "nor",
        "double", "seat", "continue", "block", "chart", "hat", "sell", "success",
        "company", "subtract", "event", "particular", "deal", "swim", "term",
        "opposite", "wife", "shoe", "shoulder", "spread", "arrange", "camp", "invent",
        "cotton", "born", "determine", "quart", "nine", "truck", "noise", "level",
        "chance", "gather", "shop", "stretch", "throw", "shine", "property", "column",
        "molecule", "select", "wrong", "gray", "repeat", "require", "broad", "prepare",
        "salt", "nose", "plural", "anger", "claim", "continent"
    ]
    
    static let SPANISH = [
        "como", "I", "su", "que", "él", "era", "para", "en", "son", "con", "ellos",
        "ser", "en", "uno", "tener", "este", "desde", "por", "caliente", "palabra",
        "pero", "qué", "algunos", "es", "lo", "usted", "o", "tenido", "la", "de", "a",
        "y", "un", "en", "nos", "lata", "fuera", "otros", "eran", "que", "hacer", "su",
        "tiempo", "si", "lo hará", "cómo", "dicho", "un", "cada", "decir", "hace",
        "conjunto", "tres", "querer", "aire", "así", "también", "jugar", "pequeño",
        "fin", "poner", "casa", "leer", "mano", "puerto", "grande", "deletrear",
        "añadir", "incluso", "tierra", "aquí", "debe", "grande", "alto", "tal", "siga",
        "acto", "por qué", "preguntar", "hombres", "cambio", "se fue", "luz", "tipo",
        "fuera", "necesitará", "casa", "imagen", "tratar", "nosotros", "de nuevo",
        "animal", "punto", "madre", "mundo", "cerca", "construir", "auto", "tierra",
        "padre", "cualquier", "nuevo", "trabajo", "parte", "tomar", "conseguir",
        "lugar", "hecho", "vivir", "donde", "después", "espalda", "poco", "sólo",
        "ronda", "hombre", "años", "vino", "show", "cada", "buena", "me", "dar",
        "nuestro", "bajo", "nombre", "muy", "a través de", "sólo", "forma", "frase",
        "gran", "pensar", "decir", "ayudar", "bajo", "línea", "ser distinto", "a su vez",
        "causa", "mucho", "significará", "antes", "movimiento", "derecho", "niño",
        "viejo", "demasiado", "misma", "ella", "todo", "hay", "cuando", "hasta", "uso",
        "su", "camino", "acerca", "muchos", "entonces", "ellos", "escribir", "haría",
        "como", "así", "éstos", "su", "largo", "hacer", "cosa", "ver", "él", "dos",
        "tiene", "buscar", "más", "día", "podía", "ir", "venir", "hizo", "número",
        "sonar", "no", "más", "personas", "mi", "sobre", "saber", "agua", "que",
        "llamada", "primero", "que", "puede", "abajo", "lado", "estado", "ahora",
        "encontrar", "cabeza", "de pie", "propio", "página", "debería", "país",
        "encontrado", "respuesta", "escuela", "crecer", "estudio", "todavía", "aprender",
        "planta", "cubierta", "alimentos", "sol", "cuatro", "entre", "estado", "mantener",
        "ojo", "nunca", "último", "dejar", "pensado", "ciudad", "árbol", "cruzar",
        "granja", "duro", "inicio", "podría", "historia", "sierra", "ahora", "mar",
        "dibujar", "izquierda", "tarde", "ejecutar", "no", "mientras", "prensa",
        "Cerrar", "noche", "reales", "vida", "pocos", "norte", "libro", "llevar",
        "tomó", "ciencia", "comer", "habitación", "amigo", "comenzó", "gusta", "peces",
        "montaña", "Deténgase", "una vez", "base de", "escuchar", "caballo", "cortada",
        "seguro", "ver", "colores", "cara", "madera", "principal", "abierta", "parecer",
        "juntos", "próximo", "blanco", "niños", "comenzar", "conseguido", "caminar",
        "ejemplo", "aliviar", "papel", "grupo", "siempre", "música", "los", "ambos",
        "marca", "menudo", "carta", "hasta", "milla", "río", "coche", "pies", "cuidado",
        "segundo", "suficiente", "llano", "chica", "habitual", "joven", "listo",
        "por encima de", "nunca", "rojo", "lista", "aunque", "sentir", "charla",
        "pájaro", "pronto", "cuerpo", "perro", "familia", "directa", "plantear",
        "dejar", "canción", "medir", "puerta", "producto", "negro", "corto", "numeral",
        "clase", "viento", "pregunta", "suceder", "completo", "buque", "zona", "medio",
        "roca", "orden", "fuego", "sur", "problema", "pieza", "dicho", "sabía", "pasar",
        "desde", "cima", "todo", "rey", "calle", "pulgadas", "multiplicar", "nada",
        "curso", "quedarse", "rueda", "completo", "fuerza", "azul", "objeto", "decidir",
        "superficie", "profunda", "luna", "isla", "pie", "sistema", "ocupado", "prueba",
        "registro", "barco", "común", "oro", "posible", "plano", "lugar", "seco",
        "maravilla", "risa", "mil", "hace", "corrió", "comprobar", "juego", "forma",
        "equiparar", "caliente", "señorita", "traído", "calor", "nieve", "neumáticos",
        "traer", "sí", "distante", "llenar", "al este", "pintar", "idioma", "entre",
        "unidad", "potencia", "ciudad", "fina", "cierto", "volar", "caer", "conducir",
        "grito", "oscuro", "máquina", "nota", "espere", "plan de", "figura", "estrella",
        "caja", "sustantivo", "campo", "resto", "correcta", "capaz", "libra", "hecho",
        "belleza", "unidad", "destacado", "contener", "delante", "enseñar", "semana",
        "último", "dio", "verde", "oh", "rápido", "desarrollar", "océano", "caliente",
        "libre", "minuto", "fuerte", "especial", "mente", "detrás", "claro", "cola",
        "Produce", "hecho", "espacio", "oído", "mejor", "horas", "mejor", "verdadero",
        "durante", "cien", "cinco", "recordar", "paso", "temprana", "mantenga", "oeste",
        "suelo", "interés", "llegar", "rápido", "verbo", "cantar", "escuchar", "seis",
        "mesa", "viajes", "menos", "mañana", "diez", "sencilla", "varios", "vocal",
        "hacia", "guerra", "sentar", "contra", "patrón", "lenta", "centro", "amar",
        "persona", "dinero", "servir", "aparecerá", "carretera", "mapa", "lluvia",
        "regla", "gobernar", "Halar", "frío", "aviso", "voz", "energía", "caza",
        "probable", "cama", "hermano", "huevo", "paseo", "celular", "creer", "quizás",
        "recoger", "repentina", "contar", "plaza", "razón", "longitud", "representar",
        "arte", "sujeto", "región", "tamaño", "variar", "resolver", "hablar", "peso",
        "general", "hielo", "materia", "círculo", "par", "incluir", "brecha", "sílaba",
        "sentido", "gran", "bola", "aún", "ola", "caer", "corazón", "am", "presente",
        "pesada", "danza", "motor", "posición", "brazo", "amplio", "vela", "materiales",
        "fracción", "bosque", "sentarse", "carrera", "ventana", "tienda", "verano",
        "tren", "sueño", "demostrar", "solitario", "pierna", "ejercicio", "pared",
        "capturas", "monte", "desear", "cielo", "bordo", "alegría", "invierno",
        "satélite", "escrito", "salvaje", "instrumento", "guardado", "vidrio", "hierba",
        "vaca", "trabajo", "borde", "signo", "visita", "pasado", "suave", "diversión",
        "brillante", "gas", "tiempo", "mes", "millones", "soportar", "acabado", "feliz",
        "esperanza", "flor", "vestir", "extraño", "se ha ido", "comercio", "melodía",
        "viaje", "oficina", "recibir", "fila", "boca", "exacta", "símbolo", "morir",
        "menos", "problema", "grito", "excepto", "escribió", "semilla", "tono",
        "unirse", "sugerir", "limpia", "rotura", "dama", "patio", "aumentando", "mal",
        "golpe", "aceite", "sangre", "tocar", "creció", "ciento", "mezclar", "equipo",
        "alambre", "costo", "perdido", "marrón", "desgaste", "jardín", "igual",
        "enviado", "elegir", "cayó", "encajar", "fluir", "justo", "banco", "recoger",
        "guardar", "el control", "decimal", "oído", "demás", "bastante", "rompió",
        "caso", "medio", "matar", "hijo", "lago", "momento", "escala", "fuerte",
        "primavera", "observar", "niño", "recta", "consonante", "nación", "diccionario",
        "leche", "velocidad", "método", "órgano", "pagar", "edad", "sección", "vestido",
        "nube", "sorpresa", "tranquila", "piedra", "pequeño", "ascenso", "fresco",
        "diseño", "pobre", "mucho", "experimento", "inferior", "clave", "hierro",
        "sola", "palillo", "plana", "veinte", "piel", "sonrisa", "pliegue", "agujero",
        "saltar", "bebé", "ocho", "pueblo", "se reúnen", "raíz", "comprar", "aumentar",
        "resolver", "de metal", "si", "empujar", "siete", "párrafo", "tercero", "deberá",
        "en espera", "pelo", "describir", "cocinero", "piso", "ya sea", "resultado",
        "quemar", "colina", "seguro", "gato", "siglo", "considerar", "tipo", "ley",
        "bit", "costa", "copia", "frase", "silencio", "de altura", "arena", "suelo",
        "rollo", "temperatura", "dedo", "industria", "valor", "lucha", "mentira",
        "batir", "excitar", "naturales", "vista", "sentido", "de capital", "no lo hará",
        "silla", "peligro", "fruta", "rica", "de espesor", "soldado", "proceso",
        "operar", "práctica", "separada", "difícil", "médico", "por favor", "proteger",
        "mediodía", "de cultivos", "moderno", "elemento", "golpear", "estudiante",
        "esquina", "partido", "suministro", "cuya", "localizar", "anillo", "carácter",
        "insecto", "capturado", "período", "indicar", "Radio", "habló", "átomo",
        "humana", "historia", "efecto", "eléctrica", "esperar", "hueso", "ferrocarril",
        "imaginar", "proporcionar", "acuerdo", "por tanto", "suave", "mujer", "capitán",
        "adivinar", "necesario", "agudo", "ala", "crear", "vecino", "lavado", "bate",
        "más bien", "multitud", "maíz", "comparar", "poema", "cadena", "campana",
        "dependerá", "carne", "frotar", "tubo", "famoso", "dólar", "corriente", "miedo",
        "vista", "delgado", "triángulo", "planeta", "prisa", "jefe", "colonia", "reloj",
        "mina", "empate", "entrar", "importante", "fresco", "búsqueda", "enviar",
        "amarillo", "pistola", "permitir", "print", "muerto", "lugar", "desierto",
        "traje", "actual", "ascensor", "rosa", "llegar", "master", "pista", "padre",
        "orilla", "división", "hoja", "sustancia", "favorecer", "conectar", "mensaje",
        "pasar", "acorde", "grasa", "contento", "originales", "cuota", "estación",
        "papá", "pan", "cobrar", "adecuada", "barra", "oferta", "segmento", "esclavo",
        "pato", "instantánea", "mercado", "grado", "poblar", "polluelo", "querido",
        "enemigo", "responder", "bebida", "producirse", "apoyo", "discurso", "naturaleza",
        "alcance", "vapor", "movimiento", "camino", "líquido", "log", "significado",
        "cociente", "dientes", "concha", "cuello", "oxígeno", "azúcar", "muerte",
        "bastante", "habilidad", "mujeres", "temporada", "solución", "imán", "plata",
        "gracias", "rama", "partido", "sufijo", "especialmente", "higo", "miedo",
        "enorme", "hermana", "acero", "discutir", "adelante", "similar", "guiar",
        "experiencia", "puntuación", "manzana", "comprado", "llevado", "pitch", "abrigo",
        "masa", "tarjeta", "banda", "cuerda", "deslizamiento", "ganar", "soñar", "noche",
        "condición", "pienso", "herramienta", "totales", "básico", "olor", "valle", "ni",
        "doble", "asiento", "continuar", "bloque", "tabla", "sombrero", "vender",
        "éxito", "empresa", "restar", "evento", "particular", "acuerdo", "nadar",
        "plazo", "opuesta", "esposa", "zapato", "hombro", "propagación", "organizar",
        "campamento", "inventar", "algodón", "nacido", "determinar", "cuarto de galón",
        "nueve", "camión", "ruido", "nivel", "oportunidad", "reunir", "tienda", "tramo",
        "lanzar", "brillo", "propiedad", "columna", "molécula", "seleccionar", "mal",
        "gris", "repita", "exigir", "amplio", "preparar", "sal", "nariz", "plurales",
        "cólera", "reclamación", "continente"
    ]
    
    static let JAPANESE = [
        "ように", "私は", "彼の", "その", "彼", "た", "ために", "上の", "アール", "とともに",
        "彼ら", "ある", "アット", "一つ", "持っている", "この", "から", "バイ", "ホット",
        "言葉", "しかし", "何", "いくつかの", "です", "それ", "あなた", "または", "持っていた",
        "インクルード", "の", "へ", "そして", "は", "で", "我々", "缶", "アウト", "その他",
        "だった", "これ", "やる", "それらの", "時間", "もし", "意志", "方法", "前記", "の",
        "それぞれ", "言う", "し", "セット", "個", "欲しい", "空気", "よく", "また", "遊ぶ",
        "小さい", "終わり", "置く", "ホーム", "読む", "手", "ポート", "大きい", "スペル",
        "加える", "さらに", "土地", "ここに", "しなければならない", "大きい", "高い", "そのような",
        "続く", "行為", "なぜ", "頼む", "人々", "変更", "行ってきました", "光", "種類", "オフ",
        "必要", "家", "絵", "試す", "私たち", "再び", "動物", "ポイント", "母", "世界", "近く",
        "ビルド", "自己", "地球", "父", "任意の", "新しい", "仕事", "パート", "取る", "ゲット",
        "場所", "製", "暮らす", "どこ", "後に", "バック", "少し", "唯一の", "ラウンド", "男",
        "年", "来た", "ショー", "すべての", "良い", "私に", "与える", "私たちの", "下", "名前",
        "非常に", "スルー", "ただ", "フォーム", "文", "素晴らしい", "思う", "言う", "助け",
        "低い", "ライン", "異なる", "ターン", "原因", "ずっと", "意味する", "前に", "移動",
        "権利", "男の子", "古い", "あまりに", "同じ", "彼女", "すべて", "そこ", "時", "アップ",
        "使用", "あなたの", "道", "約", "多くの", "その後", "それら", "書く", "でしょう",
        "ような", "そう", "これらの", "彼女の", "長い", "作る", "もの", "見る", "彼に", "二つ",
        "があります", "見える", "多くの", "日", "可能性", "行く", "来る", "やった", "番号",
        "聞こえる", "いいえ", "最も", "人々", "私の", "オーバー", "知っている", "水", "比べて",
        "コール", "最初の", "誰", "よい", "ダウン", "サイド", "き", "今", "見つける", "ヘッド",
        "スタンド", "独自の", "ページ", "べき", "国", "発見", "答え", "学校", "成長する", "研究",
        "まだ", "学ぶ", "植物", "カバー", "食品", "太陽", "つの", "間に", "状態", "キープ",
        "目", "ネバー", "最後の", "てみましょう", "考え", "街", "ツリー", "クロス", "農場",
        "ハード", "スタート", "可能性がある", "物語", "のこぎり", "遠く", "海", "描く", "左",
        "遅く", "ラン", "ない", "一方、", "プレス", "クローズ", "夜", "リアル", "生活", "少数",
        "北", "ブック", "運ぶ", "かかった", "科学", "食べる", "部屋", "友人", "始まった",
        "アイデア", "魚", "山", "停止", "一度", "ベース", "聞く", "馬", "カット", "確か",
        "見る", "カラー", "顔", "木材", "メイン", "オープン", "見える", "一緒に", "次", "白",
        "子どもたち", "始まる", "だ", "歩く", "例", "和らげる", "紙", "グループ", "常に", "音楽",
        "それらの", "両方", "マーク", "しばしば", "手紙", "まで、", "マイル", "川", "カー",
        "フィート", "介護", "第2", "十分な", "平野", "女の子", "いつもの", "若い", "レディー",
        "上記", "今までに", "赤", "リスト", "しかし", "感じる", "トーク", "鳥", "すぐに",
        "ボディ", "犬", "家族", "ダイレクト", "ポーズ", "去る", "歌", "測定", "ドア", "製品",
        "黒", "短い", "数字", "クラス", "風", "質問", "起こる", "完全な", "船", "エリア",
        "半分", "岩", "オーダー", "火災", "南", "問題", "作品", "言われ", "知っていた", "合格",
        "以来", "トップ", "全体", "王", "ストリート", "インチ", "掛ける", "何も", "もちろん",
        "滞在", "ホイール", "フル", "力", "ブルー", "オブジェクト", "決定する", "表面", "深い",
        "ムーン", "島", "足", "システム", "忙しい", "テスト", "記録", "ボート", "一般的な",
        "ゴールド", "可能", "飛行機", "代わり", "ドライ", "不思議", "笑い", "千の", "前", "走った",
        "チェック", "ゲーム", "形状", "一致する", "ホット", "ミス", "た", "熱", "雪", "タイヤ",
        "持って来る", "はい", "遠い", "埋める", "東", "ペイント", "言語", "の間で", "ユニット",
        "パワー", "町", "罰金", "特定の", "飛ぶ", "落ちる", "鉛", "泣く", "暗い", "マシン",
        "ノート", "待つ", "計画", "図", "スター", "ボックス", "名詞", "フィールド", "残り",
        "正しい", "できる", "ポンド", "終わった", "美しさ", "ドライブ", "立っていた", "含む",
        "フロント", "教える", "週", "ファイナル", "与えた", "緑", "ああ", "クイック", "開発する",
        "海", "暖かい", "無料で", "分", "強い", "特別", "心", "背後に", "明確な", "テール",
        "作る", "事実", "スペース", "聞いた", "ベスト", "時間", "良い", "真の", "間に", "百",
        "五", "覚えている", "ステップ", "早い", "ホールド", "西", "地面", "関心", "リーチ",
        "速い", "動詞", "歌う", "聞く", "六", "テーブル", "旅行", "レス", "朝", "十", "シンプル",
        "いくつかの", "母音", "の方へ", "戦争", "産む", "に対する", "パターン", "遅い", "センター",
        "愛", "人", "マネー", "サーブ", "見える", "道路", "マップ", "雨", "ルール", "支配する",
        "引っ張る", "寒い", "予告", "声", "エネルギー", "狩り", "ありそうな", "ベッド", "兄",
        "卵", "乗る", "セル", "信じる", "たぶん", "選ぶ", "突然の", "カウント", "広場", "理由",
        "長さ", "表す", "アート", "テーマ", "地域", "サイズ", "変える", "落ち着く", "話す",
        "重さ", "一般", "アイス", "問題", "サークル", "ペア", "含める", "分割", "音節", "フェルト",
        "壮大な", "ボール", "まだ", "波", "ドロップ", "心", "AM", "現在", "重い", "ダンス",
        "エンジン", "ポジション", "アーム", "広い", "帆", "材料", "分数", "森", "座る", "レース",
        "窓", "店", "夏", "列車", "スリープ", "証明する", "ローン", "レッグ", "エクササイズ",
        "壁", "キャッチ", "マウント", "希望", "空", "ボード", "喜び", "冬", "土", "書かれた",
        "ワイルド", "楽器", "保管", "ガラス", "草", "乳牛", "仕事", "エッジ", "看板", "訪問",
        "過去", "ソフト", "楽しい", "明るい", "ガス", "天候", "月", "万", "クマ", "仕上げ",
        "幸せな", "希望", "花", "衣服を着せる", "奇妙な", "いなくなった", "トレード", "メロディー",
        "旅", "オフィス", "受け取る", "行", "口", "正確な", "シンボル", "死ぬ", "最低", "トラブル",
        "シャウト", "ただし", "書いた", "シード", "トーン", "参加する", "提案する", "クリーン",
        "ブレーク", "女性", "庭", "上昇", "悪い", "打撃", "オイル", "血", "触れる", "成長した",
        "セント", "ミックス", "チーム", "ワイヤー", "コスト", "失われた", "ブラウン", "着用",
        "庭", "等しい", "送信された", "選ぶ", "落ちた", "フィット", "流れ", "フェア", "銀行",
        "集める", "保存", "コントロール", "進", "耳", "ほかに", "かなり", "壊した", "ケース",
        "ミドル", "殺す", "息子", "湖", "瞬間", "スケール", "騒々しい", "春", "観察する", "子ども",
        "ストレート", "子音", "国家", "辞書", "ミルク", "スピード", "方法", "オルガン", "支払い",
        "年齢", "セクション", "ドレス", "クラウド", "驚き", "静かな", "石", "小さな", "登る",
        "涼しい", "デザイン", "貧しい", "たくさん", "実験", "ボトム", "キー", "鉄", "シングル",
        "スティック", "フラット", "個の", "スキン", "笑顔", "しわ", "穴", "ジャンプ", "赤ちゃん",
        "人", "村", "大会", "ルート", "買う", "上げる", "解く", "金属", "かどうか", "プッシュ",
        "7", "パラグラフ", "第3", "しなければならない", "ハンドヘルド", "髪", "説明する", "料理人",
        "床", "どちら", "結果", "燃やす", "丘", "金庫", "猫", "世紀", "考える", "タイプ", "法則",
        "ビット", "海岸", "コピー", "フレーズ", "サイレント", "背の高い", "砂", "土壌", "ロール",
        "温度", "指", "業界", "値", "戦い", "うそ", "ビート", "エキサイト", "ナチュラル", "ビュー",
        "感覚", "首都", "ないでしょう", "椅子", "危険", "フルーツ", "金持ち", "厚い", "兵士",
        "プロセス", "操作する", "練習", "別", "難しい", "医師", "どうぞ", "守る", "正午", "作物",
        "モダン", "要素", "ヒット", "学生", "コーナー", "パーティー", "サプライ", "その", "検索する",
        "リング", "キャラクター", "昆虫", "キャッチ", "期間", "示す", "ラジオ", "スポーク", "アトム",
        "人間", "歴史", "効果", "エレクトリック", "期待する", "骨", "レール", "想像する", "提供する",
        "同意する", "このようにして", "優しい", "女", "キャプテン", "推測", "必要", "シャープ",
        "ウイング", "作る", "隣人", "ウォッシュ", "バット", "むしろ", "群衆", "トウモロコシ",
        "比較する", "詩", "文字列", "鐘", "決まる", "肉", "こする", "チューブ", "有名な", "ドル",
        "ストリーム", "恐怖", "視力", "薄い", "三角形", "惑星", "急ぐ", "チーフ", "コロニー",
        "クロック", "地雷", "ネクタイ", "入力する", "主要な", "新鮮な", "検索", "送信", "黄色",
        "銃", "許可する", "印刷", "死んだ", "スポット", "砂漠", "スーツ", "現在の", "リフト",
        "ローズ", "届く", "マスター", "トラック", "親", "海岸", "分裂", "シート", "物質", "好む",
        "接続する", "ポスト", "過ごす", "和音", "脂肪", "うれしい", "オリジナル", "シェア", "駅",
        "お父さん", "パン", "充電", "適切な", "バー", "申し出", "セグメント", "スレーブ", "アヒル",
        "インスタント", "市場", "度", "投入する", "ひよこ", "かわいい", "敵", "返事", "ドリンク",
        "起こる", "サポート", "スピーチ", "自然", "レンジ", "スチーム", "モーション", "パス",
        "液体", "ログ", "意味", "商", "歯牙", "シェル", "首", "酸素", "砂糖", "死", "かわいい",
        "スキル", "女性たち", "シーズン", "ソリューション", "マグネット", "銀", "感謝", "ブランチ",
        "マッチ", "サフィックス", "特に", "イチジク", "恐れて", "巨大な", "姉妹", "スチール",
        "話し合う", "フォワード", "同じような", "ガイド", "経験", "スコア", "リンゴ", "買った",
        "主導", "ピッチ", "コート", "マス", "カード", "バンド", "ロープ", "スリップ", "勝つ",
        "夢", "夕べ", "条件", "フィード", "ツール", "合計", "基本", "匂い", "谷", "も",
        "ダブル", "座席", "続ける", "ブロック", "チャート", "帽子", "売る", "成功", "会社",
        "引く", "イベント", "特定の", "契約", "泳ぐ", "言葉", "反対", "妻", "靴", "肩",
        "スプレッド", "アレンジ", "キャンプ", "発明する", "綿", "ボルン", "決定する", "クォート",
        "人", "トラック", "ノイズ", "レベル", "チャンス", "集まる", "ショップ", "ストレッチ",
        "投げる", "輝き", "財産", "コラム", "分子", "選択する", "間違った", "グレー", "リピート",
        "必要とする", "幅広い", "準備する", "塩", "鼻", "複数", "怒り", "請求", "大陸"
    ]
}
